OpenCV notebook - ©Arkaprabha Majumdar

# #1. Face Detection

In [1]:
import cv2
import numpy as np

In [ ]:
#initialize the haar frontal face cascade
face_classifier = cv2.CascadeClassifier("/home/arkaprabham/Desktop/Deep_Learning_Udemy/my_project_env/lib/python3.8/site-packages/cv2/data/haarcascade_frontalface_default.xml")

image = cv2.imread("/home/arkaprabham/Desktop/Deep_Learning_Udemy/img/Animals/humans/humans.jpg")

gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray,1.3,5)

if faces.size:
    for (x,y,w,h) in faces:
        cv2.rectangle(image,(x,y),(x+w,y+h),(0,0,255),2)
        cv2.imshow("Faces detected",image)
        cv2.waitKey(0)

cv2.destroyAllWindows()

In [ ]:
#initialize the haar frontal face cascade
face_classifier = cv2.CascadeClassifier("/home/arkaprabham/Desktop/Deep_Learning_Udemy/my_project_env/lib/python3.8/site-packages/cv2/data/haarcascade_frontalface_default.xml")

#Let us put the above code into a function and we'll do something nice !
def face_detect(image):
    gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    
    faces = face_classifier.detectMultiScale(gray,1.3,5)

    if list(faces):
        for (x,y,w,h) in faces:
            cv2.rectangle(image,(x,y),(x+w,y+h),(0,0,255),2)
    else:
        return image
    return image


#remember how we accessed the webcam in our initial projects?
cap = cv2.VideoCapture(0)
i=0
while True:
    print(i)
    _,frame=cap.read()
    cv2.imshow("Face detector",face_detect(frame))
    i+=1
    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()
#Excuse the frame number being printed, but I like to see my code running each loop

# #2. Combining eye detection with face directly for webcam


In [8]:
#initialize the haar frontal face classifier AND eye classifier
face_classifier = cv2.CascadeClassifier("/home/arkaprabham/Desktop/Deep_Learning_Udemy/my_project_env/lib/python3.8/site-packages/cv2/data/haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier("/home/arkaprabham/Desktop/Deep_Learning_Udemy/my_project_env/lib/python3.8/site-packages/cv2/data/haarcascade_eye.xml")


#I copy pasted the code above and made modifications...try figuring it out yourself. NOT THAT HARD!
def face_eye_detect(image):
    blur = cv2.GaussianBlur(image,(3,3),1)
    gray = cv2.cvtColor(blur,cv2.COLOR_BGR2GRAY)
    
    faces = face_classifier.detectMultiScale(gray,1.3,5)
    
    if list(faces):
        for (x,y,w,h) in faces:
            cv2.rectangle(image,(x,y),(x+w,y+h),(0,0,255),2)
            roi_gray=gray[y:y+h,x:x+w]
            roi_color=image[y:y+h,x:x+w]
            print(roi_gray)
            if list(roi_gray):
                eyes = eye_classifier.detectMultiScale(roi_gray)
                if list(eyes):
                    print("Eyes")
                    for (ex,ey,ew,eh) in eyes:
                        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(255,0,0),2)
                else:
                    print("No eyes")
    else:
        return image
    return image


#remember how we accessed the webcam in our initial projects?
cap = cv2.VideoCapture(0)
i=0
while True:
    print(i)
    _,frame=cap.read()
    cv2.imshow("Face detector",face_eye_detect(frame))
    i+=1
    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()
#Excuse the frame number being printed, but I like to see my code running each loop

0
[[ 17  14  13 ... 127 127 128]
 [ 17  15  14 ... 127 127 127]
 [ 17  16  15 ... 127 127 127]
 ...
 [ 42  42  42 ... 122 121 121]
 [ 43  42  41 ... 122 120 120]
 [ 42  40  39 ... 122 120 120]]
No eyes
1
[[ 16  16  16 ... 129 129 129]
 [ 17  17  16 ... 130 129 130]
 [ 18  17  16 ... 130 129 128]
 ...
 [ 42  42  41 ... 120 120 119]
 [ 43  42  41 ... 119 119 118]
 [ 42  41  41 ... 118 118 117]]
Eyes
2
[[ 18  20  19 ... 138 138 137]
 [ 19  20  20 ... 137 137 137]
 [ 20  20  20 ... 136 135 136]
 ...
 [ 49  48  47 ... 130 130 129]
 [ 48  48  47 ... 129 129 129]
 [ 48  49  48 ... 129 129 129]]
Eyes
3
[[ 15  14  14 ... 136 135 133]
 [ 14  14  15 ... 136 135 134]
 [ 15  15  16 ... 135 135 133]
 ...
 [ 47  47  48 ... 127 127 128]
 [ 47  48  48 ... 129 129 129]
 [ 46  47  48 ... 130 128 128]]
Eyes
4
[[ 17  18  19 ... 136 135 134]
 [ 18  19  20 ... 135 135 135]
 [ 19  20  20 ... 134 134 135]
 ...
 [ 46  45  43 ... 129 127 127]
 [ 46  46  45 ... 130 129 128]
 [ 45  46  47 ... 130 129 129]]
Eyes
5


Eyes
42
[[ 26  26  26 ... 123 116 112]
 [ 26  26  26 ... 115 111 108]
 [ 26  26  25 ... 110 108 107]
 ...
 [ 69  69  63 ... 133 132 132]
 [ 70  69  64 ... 135 134 134]
 [ 69  69  65 ... 136 135 135]]
No eyes
43
[[ 30  29  29 ... 131 128 124]
 [ 29  29  28 ... 128 123 119]
 [ 27  27  27 ... 123 119 115]
 ...
 [ 56  56  55 ... 136 135 134]
 [ 54  54  54 ... 135 135 134]
 [ 55  56  55 ... 134 134 134]]
No eyes
44
[[ 28  27  27 ... 106 102 101]
 [ 29  27  26 ... 107 104 103]
 [ 29  27  25 ... 108 105 103]
 ...
 [ 51  51  53 ... 132 132 133]
 [ 48  50  52 ... 132 133 134]
 [ 47  50  52 ... 131 132 134]]
No eyes
45
[[ 28  28  29 ... 111 111 110]
 [ 28  28  28 ... 107 109 109]
 [ 27  27  27 ... 107 108 108]
 ...
 [ 50  52  54 ... 133 134 135]
 [ 47  50  52 ... 134 135 135]
 [ 46  47  49 ... 133 135 136]]
Eyes
46
[[ 33  30  28 ... 109 106 104]
 [ 33  31  28 ... 108 106 104]
 [ 32  30  29 ... 106 105 103]
 ...
 [ 32  31  32 ... 132 132 132]
 [ 30  30  31 ... 132 132 131]
 [ 32  31  31 ... 132 1

[[ 25  24  24 ... 140 140 139]
 [ 24  25  25 ... 139 139 139]
 [ 24  25  25 ... 139 138 138]
 ...
 [ 48  47  45 ... 134 135 135]
 [ 47  46  44 ... 135 136 135]
 [ 47  45  43 ... 134 135 134]]
Eyes
89
[[ 24  23  22 ... 139 138 138]
 [ 24  23  23 ... 139 139 138]
 [ 24  24  24 ... 139 138 138]
 ...
 [ 24  25  24 ... 103 103 103]
 [ 23  23  23 ... 101 101 101]
 [ 23  23  23 ... 102 100 100]]
Eyes
90
[[ 22  24  24 ... 139 138 138]
 [ 23  23  24 ... 140 138 137]
 [ 23  23  24 ... 139 138 138]
 ...
 [ 42  43  43 ... 131 132 133]
 [ 42  42  42 ... 131 131 132]
 [ 41  42  43 ... 131 130 131]]
Eyes
91
[[ 24  25  24 ... 139 138 137]
 [ 24  24  23 ... 139 138 137]
 [ 24  24  24 ... 139 138 137]
 ...
 [ 35  37  40 ... 132 132 132]
 [ 33  37  40 ... 132 131 131]
 [ 33  37  41 ... 131 131 131]]
Eyes
92
[[ 24  23  22 ... 138 138 137]
 [ 22  21  21 ... 137 137 137]
 [ 20  20  20 ... 136 136 136]
 ...
 [ 38  39  39 ... 129 129 129]
 [ 38  39  40 ... 124 125 126]
 [ 38  39  40 ... 111 114 117]]
Eyes
93


132
133
134
135
[[ 19  17  17 ... 127 126 127]
 [ 18  16  15 ... 127 127 127]
 [ 17  16  15 ... 129 129 129]
 ...
 [ 40  41  41 ... 122 123 123]
 [ 40  40  39 ... 125 125 124]
 [ 40  39  37 ... 125 124 124]]
Eyes
136
[[ 17  19  20 ... 130 129 130]
 [ 16  19  19 ... 130 130 131]
 [ 17  18  18 ... 129 130 131]
 ...
 [ 42  41  39 ... 122 123 124]
 [ 40  39  38 ... 122 123 124]
 [ 38  38  38 ... 122 122 123]]
Eyes
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
[[21 20 18 ... 86 87 84]
 [19 18 17 ... 86 87 86]
 [16 16 15 ... 83 84 85]
 ...
 [88 93 95 ... 45 47 49]
 [87 94 96 ... 47 48 49]
 [86 93 96 ... 49 50 50]]
Eyes
162
[[ 20  21  23 ...  88  86  83]
 [ 21  21  21 ...  87  86  84]
 [ 21  20  21 ...  86  85  84]
 ...
 [ 99  99  99 ...  52  51  52]
 [100 100 100 ...  51  51  51]
 [101 102 102 ...  50  51  50]]
No eyes
163
[[ 18  19  23 ...  86  85  82]
 [ 18  19  22 ...  87  85  82]
 [ 19  20  22 ...  85  83  81]
 ...
 [104 103 103 ...  

[[ 59  53  45 ...  80  79  75]
 [ 56  51  44 ...  74  72  71]
 [ 52  47  40 ...  68  68  68]
 ...
 [ 20  22  21 ... 125 125 123]
 [ 22  23  22 ... 124 123 122]
 [ 24  24  22 ... 125 124 123]]
Eyes
204
[[ 43  36  31 ...  68  71  72]
 [ 38  33  30 ...  67  71  73]
 [ 34  31  31 ...  70  75  81]
 ...
 [ 24  24  23 ... 122 123 122]
 [ 21  20  20 ... 121 122 123]
 [ 20  18  19 ... 121 122 123]]
Eyes
205
[[ 64  62  57 ...  68  73  78]
 [ 60  58  54 ...  72  76  76]
 [ 57  55  53 ...  74  75  74]
 ...
 [ 24  23  23 ... 121 122 122]
 [ 25  24  24 ... 120 122 122]
 [ 25  24  24 ... 119 121 122]]
Eyes
206
[[ 55  47  37 ...  65  63  67]
 [ 56  46  34 ...  66  65  70]
 [ 53  44  33 ...  64  65  69]
 ...
 [ 25  26  26 ... 123 123 122]
 [ 24  24  25 ... 122 121 120]
 [ 21  22  23 ... 120 121 121]]
Eyes
207
[[ 54  46  40 ...  54  54  55]
 [ 50  43  37 ...  55  57  58]
 [ 47  40  34 ...  56  59  60]
 ...
 [ 22  23  24 ... 115 116 117]
 [ 24  23  23 ... 117 118 119]
 [ 25  24  23 ... 120 120 120]]
No e

[[ 79  77  75 ... 107 104 102]
 [ 79  78  75 ... 109 105 101]
 [ 79  77  75 ... 113 106 100]
 ...
 [ 31  29  28 ... 120 117 112]
 [ 30  29  28 ... 121 116 111]
 [ 31  30  30 ... 121 116 110]]
Eyes
247
[[ 71  69  68 ... 112 106 101]
 [ 70  69  69 ... 111 105 101]
 [ 70  69  67 ... 112 106 103]
 ...
 [ 28  27  27 ... 123 121 120]
 [ 28  26  27 ... 122 123 122]
 [ 26  26  27 ... 121 122 123]]
Eyes
248
[[ 44  39  34 ... 126 126 126]
 [ 41  35  30 ... 126 126 126]
 [ 38  30  27 ... 126 126 127]
 ...
 [ 28  29  31 ... 123 122 120]
 [ 27  28  30 ... 121 120 119]
 [ 26  28  29 ... 120 119 119]]
Eyes
249
[[ 77  77  75 ... 106 104 102]
 [ 75  74  74 ... 105  99  93]
 [ 74  75  76 ... 102  92  84]
 ...
 [ 38  34  31 ... 111 104 102]
 [ 37  33  30 ... 107 102 100]
 [ 36  32  29 ... 104 100 100]]
Eyes
250
[[ 75  73  70 ... 119 115 109]
 [ 74  73  71 ... 119 116 110]
 [ 73  72  69 ... 120 118 112]
 ...
 [ 27  27  28 ... 122 122 120]
 [ 27  27  28 ... 122 120 118]
 [ 27  26  26 ... 121 120 119]]
Eyes

[[ 20  20  22 ...  64  71  84]
 [ 21  21  24 ...  61  68  84]
 [ 21  21  23 ...  61  70  88]
 ...
 [ 48  49  49 ... 126 126 125]
 [ 50  50  49 ... 126 127 126]
 [ 51  50  49 ... 125 126 125]]
Eyes
289
[[ 25  26  26 ...  86 107 117]
 [ 24  26  25 ...  89 109 117]
 [ 24  25  24 ...  97 111 117]
 ...
 [ 48  50  49 ... 123 123 124]
 [ 49  52  51 ... 123 123 123]
 [ 50  53  53 ... 124 124 123]]
Eyes
290
[[ 22  23  22 ... 102 103 103]
 [ 23  23  22 ... 112 113 113]
 [ 24  23  23 ... 115 116 115]
 ...
 [ 50  51  52 ... 125 126 126]
 [ 49  51  51 ... 126 127 126]
 [ 49  51  52 ... 124 125 124]]
Eyes
291
[[ 22  24  23 ...  91  94  91]
 [ 22  23  23 ...  88  99 102]
 [ 25  24  23 ...  84 101 110]
 ...
 [ 49  48  46 ... 124 124 123]
 [ 51  51  50 ... 126 126 125]
 [ 49  50  50 ... 124 125 125]]
Eyes
292
[[ 22  23  24 ...  82  83  85]
 [ 24  24  24 ...  94  95  95]
 [ 25  25  24 ... 105 104 103]
 ...
 [ 49  48  48 ... 123 122 123]
 [ 49  48  48 ... 121 121 121]
 [ 47  46  47 ... 121 121 122]]
Eyes

329
[[ 28  27  25 ... 112 115 114]
 [ 28  27  26 ... 114 115 115]
 [ 26  26  25 ... 117 116 117]
 ...
 [ 48  49  49 ... 121 121 122]
 [ 48  48  49 ... 122 121 122]
 [ 49  48  49 ... 122 122 122]]
No eyes
330
[[ 42  36  33 ...  83  85  92]
 [ 38  33  31 ...  90  93  98]
 [ 36  32  30 ... 100 101 104]
 ...
 [ 42  43  46 ... 120 120 120]
 [ 42  43  45 ... 121 122 122]
 [ 43  44  45 ... 121 123 122]]
Eyes
331
[[ 26  24  23 ...  87 103 112]
 [ 28  26  24 ...  96 110 117]
 [ 28  27  25 ... 106 114 118]
 ...
 [ 47  49  51 ... 123 120 119]
 [ 45  46  49 ... 121 119 118]
 [ 46  47  49 ... 121 119 119]]
Eyes
332
[[ 31  29  28 ...  85  89  97]
 [ 30  27  26 ...  97 100 104]
 [ 28  26  24 ... 107 107 108]
 ...
 [ 47  50  50 ... 123 123 122]
 [ 48  49  49 ... 123 122 120]
 [ 45  47  49 ... 122 120 118]]
Eyes
333
[[ 29  27  26 ...  90  94  97]
 [ 28  26  25 ...  96  98 100]
 [ 28  26  25 ... 101 103 103]
 ...
 [ 42  44  44 ... 121 122 121]
 [ 42  45  47 ... 123 121 120]
 [ 41  44  47 ... 122 121 120

[[ 41  39  37 ... 111 108 105]
 [ 38  37  35 ... 113 109 106]
 [ 35  34  32 ... 113 108 106]
 ...
 [ 42  43  42 ... 113 114 115]
 [ 40  42  42 ... 112 113 114]
 [ 39  40  41 ... 112 112 113]]
Eyes
376
[[ 32  31  31 ...  82  66  58]
 [ 30  29  29 ...  85  69  60]
 [ 29  29  27 ...  90  75  64]
 ...
 [ 44  43  42 ... 111 109 106]
 [ 42  41  42 ... 112 110 107]
 [ 41  41  41 ... 112 110 108]]
No eyes
377
[[30 31 30 ... 49 46 43]
 [30 31 31 ... 47 44 43]
 [28 28 29 ... 45 43 44]
 ...
 [45 45 45 ... 52 48 47]
 [42 41 41 ... 52 50 49]
 [41 39 39 ... 55 50 50]]
No eyes
378
[[22 22 23 ... 43 44 43]
 [23 24 24 ... 44 45 45]
 [24 25 24 ... 46 46 44]
 ...
 [39 40 41 ... 40 38 38]
 [40 40 41 ... 38 38 38]
 [41 41 41 ... 38 38 39]]
Eyes
379
[[19 20 20 ... 43 42 42]
 [18 19 21 ... 45 46 44]
 [19 19 21 ... 45 47 46]
 ...
 [40 40 41 ... 39 38 38]
 [39 39 40 ... 39 39 38]
 [40 40 41 ... 41 42 40]]
Eyes
380
[[27 25 25 ... 43 43 43]
 [25 24 25 ... 41 43 43]
 [25 24 26 ... 39 42 42]
 ...
 [40 41 42 ... 39

[[125 125 125 ...  39  33  28]
 [126 126 125 ...  38  34  29]
 [125 125 125 ...  38  34  30]
 ...
 [ 65  68  69 ...  40  39  36]
 [ 64  66  67 ...  40  39  37]
 [ 63  64  65 ...  41  39  37]]
Eyes
423
[[127 125 125 ...  38  33  27]
 [126 125 125 ...  38  32  28]
 [125 125 125 ...  37  32  28]
 ...
 [ 68  67  66 ...  37  36  35]
 [ 67  68  67 ...  36  35  34]
 [ 66  66  66 ...  36  35  34]]
Eyes
424
[[126 126 127 ...  45  43  40]
 [127 127 128 ...  45  43  39]
 [128 128 129 ...  46  44  40]
 ...
 [ 67  67  67 ...  42  40  38]
 [ 66  66  67 ...  42  40  39]
 [ 66  67  67 ...  43  41  39]]
Eyes
425
[[125 124 125 ...  47  48  50]
 [125 124 124 ...  45  47  50]
 [125 125 125 ...  42  45  48]
 ...
 [ 61  60  60 ...  45  45  45]
 [ 62  61  61 ...  46  46  45]
 [ 63  62  62 ...  46  45  45]]
Eyes
426
[[129 128 127 ...  50  50  51]
 [127 127 127 ...  50  49  51]
 [125 126 126 ...  48  49  49]
 ...
 [ 56  59  62 ...  45  46  46]
 [ 57  60  62 ...  45  45  46]
 [ 58  60  61 ...  46  46  46]]
Eyes

[[ 26  26  25 ...  95  94  94]
 [ 26  25  25 ...  94  94  95]
 [ 25  25  24 ...  94  94  95]
 ...
 [ 34  34  34 ... 100  99  98]
 [ 34  35  35 ... 101 100  98]
 [ 34  36  36 ... 101 101 100]]
Eyes
470
[[ 24  24  24 ...  72  75  84]
 [ 23  23  24 ...  79  84  94]
 [ 22  23  23 ...  94  98 106]
 ...
 [ 28  27  26 ...  96  97  96]
 [ 28  27  26 ...  95  95  95]
 [ 29  27  26 ...  93  93  93]]
Eyes
471
[[ 20  19  20 ... 115 120 123]
 [ 22  21  22 ... 115 121 123]
 [ 22  22  23 ... 115 122 123]
 ...
 [ 43  43  42 ...  49  49  48]
 [ 44  43  43 ...  51  51  51]
 [ 43  43  43 ...  52  52  51]]
Eyes
472
473
474
475
476
[[ 26  25  25 ... 131 130 130]
 [ 25  25  24 ... 130 130 131]
 [ 25  25  25 ... 129 130 130]
 ...
 [ 52  52  54 ... 124 124 124]
 [ 53  51  53 ... 125 125 125]
 [ 54  52  53 ... 126 126 125]]
No eyes
477
[[ 28  26  25 ... 129 129 130]
 [ 27  26  26 ... 129 129 129]
 [ 27  26  27 ... 129 130 129]
 ...
 [ 68  66  65 ... 126 125 125]
 [ 67  65  64 ... 124 124 124]
 [ 66  63  62 ...

The better the camera, the better the results basically.

In [10]:
#Here I am applying it to my video file from Crazy Rich Asians, which I definitely didn't torrent.
#My friend bought it ;)

In [9]:
#Let's try it on a video file
cap = cv2.VideoCapture('/home/arkaprabham/Downloads/Crazy.Rich.Asians.2018.720p.WEB-DL.MkvCage.ws.mkv')
i=0
while True:
    print(i)
    _,frame=cap.read()
    cv2.imshow("Face detector",face_eye_detect(frame))
    i+=1
    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
[[131 124 111 ... 114  96  81]
 [130 122 107 ... 112  95  78]
 [131 120 106 ... 111  95  78]
 ...
 [122 122 122 ... 122 124 125]
 [122 122 122 ... 122 125 125]
 [122 122 122 ... 122 126 126]]
No eyes
107
108
109
[[150 149 147 ... 121 105  89]
 [150 148 146 ... 119 103  87]
 [150 148 146 ... 117 103  87]
 ...
 [127 127 128 ... 124 124 124]
 [127 127 128 ... 123 124 125]
 [126 127 128 ... 123 124 125]]
No eyes
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
17

[[30 30 31 ... 36 37 37]
 [30 31 32 ... 37 36 36]
 [31 32 32 ... 37 36 36]
 ...
 [28 29 29 ... 30 30 30]
 [28 28 28 ... 30 30 31]
 [26 27 28 ... 30 30 31]]
Eyes
[[33 44 57 ... 41 40 39]
 [33 43 56 ... 42 40 38]
 [33 41 54 ... 38 36 34]
 ...
 [30 30 29 ... 30 28 29]
 [29 29 29 ... 30 30 31]
 [30 30 30 ... 30 32 34]]
No eyes
1276
[[31 32 32 ... 37 37 36]
 [32 32 32 ... 37 37 36]
 [31 32 34 ... 36 37 37]
 ...
 [29 29 29 ... 30 30 30]
 [29 28 29 ... 30 30 30]
 [28 28 29 ... 30 30 30]]
Eyes
[[34 45 57 ... 41 40 39]
 [33 43 55 ... 42 40 38]
 [33 41 53 ... 38 36 34]
 ...
 [30 30 29 ... 30 29 29]
 [29 29 29 ... 30 31 32]
 [30 30 30 ... 31 33 35]]
No eyes
1277
[[31 32 32 ... 37 36 36]
 [32 32 32 ... 37 36 36]
 [31 32 34 ... 37 37 37]
 ...
 [29 29 29 ... 30 30 30]
 [28 28 29 ... 30 30 31]
 [27 28 30 ... 30 30 31]]
Eyes
1278
[[31 31 32 ... 37 37 37]
 [31 32 33 ... 37 37 37]
 [31 33 34 ... 37 37 37]
 ...
 [29 29 29 ... 30 30 30]
 [28 28 29 ... 30 30 31]
 [27 28 30 ... 30 30 31]]
Eyes
1279
[[30 31 

[[30 31 32 ... 35 35 34]
 [29 30 32 ... 35 35 35]
 [30 31 33 ... 35 35 36]
 ...
 [31 31 31 ... 31 31 30]
 [31 31 31 ... 31 31 31]
 [30 30 30 ... 30 31 31]]
Eyes
[[32 42 55 ... 42 41 39]
 [32 40 53 ... 41 40 38]
 [33 39 51 ... 37 34 33]
 ...
 [30 30 29 ... 28 28 29]
 [29 30 29 ... 29 30 32]
 [30 30 30 ... 31 33 35]]
No eyes
1314
[[31 31 31 ... 35 35 35]
 [30 30 30 ... 35 35 35]
 [29 29 29 ... 36 35 35]
 ...
 [31 32 31 ... 31 31 31]
 [30 31 31 ... 31 31 31]
 [30 30 30 ... 30 30 31]]
Eyes
[[32 42 55 ... 42 41 39]
 [32 40 53 ... 41 40 38]
 [33 39 51 ... 37 34 33]
 ...
 [30 30 29 ... 28 28 29]
 [29 30 29 ... 29 30 32]
 [30 30 30 ... 31 33 35]]
No eyes
1315
[[31 31 31 ... 35 35 35]
 [30 30 30 ... 35 35 35]
 [29 29 29 ... 36 35 35]
 ...
 [31 32 31 ... 31 31 31]
 [30 31 31 ... 31 31 31]
 [30 30 30 ... 30 30 31]]
Eyes
[[32 42 55 ... 42 41 39]
 [32 40 53 ... 41 40 38]
 [33 39 51 ... 37 34 33]
 ...
 [30 30 29 ... 28 28 29]
 [29 30 29 ... 29 30 32]
 [30 30 30 ... 31 33 35]]
No eyes
1316
[[31 31 31

[[  4   5   7 ...  34  60  97]
 [  4   6   8 ...  33  55  92]
 [  5   6   7 ...  31  48  84]
 ...
 [  4   3   3 ... 142 141 140]
 [  1   1   0 ... 142 142 141]
 [  1   0   0 ... 144 144 142]]
No eyes
1612
[[  3   4   5 ...  25  39  69]
 [  4   4   6 ...  26  36  63]
 [  4   5   6 ...  24  32  53]
 ...
 [  5   5   4 ... 141 142 141]
 [  2   2   1 ... 141 142 142]
 [  1   1   1 ... 141 144 144]]
No eyes
1613
[[  4   4   4 ...  31  27  23]
 [  3   3   4 ...  33  28  23]
 [  3   4   5 ...  33  27  22]
 ...
 [  4   4   4 ... 137 137 136]
 [  1   2   2 ... 135 136 137]
 [  0   0   1 ... 136 137 138]]
No eyes
1614
[[  4   3   3 ...  20  25  44]
 [  4   4   4 ...  24  25  42]
 [  3   3   4 ...  25  26  40]
 ...
 [  1   2   2 ... 138 140 141]
 [  0   0   1 ... 139 140 143]
 [  1   1   1 ... 135 137 141]]
No eyes
1615
[[  4   4   4 ...  29  26  25]
 [  3   3   4 ...  31  28  27]
 [  3   4   5 ...  31  28  25]
 ...
 [  7   8   8 ... 136 141 142]
 [  4   4   5 ... 133 138 139]
 [  1   2   2 ... 13

[[ 35  39  35 ... 133 140 138]
 [ 35  39  35 ... 126 138 138]
 [ 35  39  34 ... 119 136 137]
 ...
 [ 21  23  20 ... 104 112 116]
 [ 20  21  19 ...  63  73  80]
 [ 19  20  18 ...  34  37  42]]
Eyes
1654
[[ 23  35  39 ... 142 141 139]
 [ 24  34  39 ... 140 140 139]
 [ 24  35  39 ... 136 139 138]
 ...
 [ 14  20  21 ...  73  81  85]
 [ 14  19  19 ...  39  43  47]
 [ 14  19  19 ...  30  27  26]]
No eyes
1655
[[ 12  23  35 ...  31  65 110]
 [ 12  23  34 ...  28  56  99]
 [ 13  23  34 ...  26  48  87]
 ...
 [  6  14  21 ...  75 107 127]
 [  6  14  21 ...  53  77  99]
 [  6  14  20 ...  34  45  60]]
Eyes
1656
[[  8  12  24 ...  26  49  91]
 [  8  13  24 ...  24  42  80]
 [  9  13  24 ...  23  35  68]
 ...
 [  1   6  14 ...  54  78 108]
 [  1   6  14 ...  41  58  83]
 [  2   6  14 ...  33  38  51]]
No eyes
1657
[[ 7 12 23 ... 20 32 65]
 [ 8 12 23 ... 22 29 57]
 [ 9 13 23 ... 22 27 50]
 ...
 [ 1  5 14 ... 53 60 82]
 [ 1  6 14 ... 46 56 79]
 [ 1  6 14 ... 38 44 62]]
Eyes
1658
[[  8  13  24 ...  3

[[23 25 29 ... 37 40 30]
 [24 29 34 ... 37 41 30]
 [25 32 39 ... 38 41 30]
 ...
 [73 59 50 ... 21 20 15]
 [64 54 49 ... 21 20 15]
 [58 53 50 ... 21 20 15]]
No eyes
1789
[[25 28 31 ... 37 40 30]
 [28 33 37 ... 37 41 30]
 [30 37 43 ... 38 41 30]
 ...
 [62 51 50 ... 21 20 15]
 [55 50 51 ... 21 20 15]
 [52 49 51 ... 21 20 15]]
No eyes
1790
[[23 26 29 ... 37 40 30]
 [24 28 33 ... 37 41 30]
 [25 31 38 ... 38 41 30]
 ...
 [66 55 52 ... 21 20 15]
 [58 51 51 ... 21 20 15]
 [54 51 50 ... 21 20 15]]
No eyes
1791
[[21 23 25 ... 23 26 37]
 [21 23 27 ... 22 26 37]
 [20 24 30 ... 21 26 38]
 ...
 [84 69 57 ... 12 15 21]
 [77 63 54 ... 12 15 21]
 [65 56 50 ... 12 15 21]]
No eyes
1792
[[25 30 35 ... 26 37 41]
 [27 34 40 ... 26 38 41]
 [29 37 44 ... 27 38 40]
 ...
 [53 51 57 ... 20 28 26]
 [49 48 55 ... 20 28 26]
 [46 46 54 ... 20 28 26]]
No eyes
1793
[[24 26 29 ... 26 37 40]
 [25 29 34 ... 26 37 41]
 [28 34 40 ... 26 38 41]
 ...
 [56 54 59 ... 20 28 26]
 [51 52 59 ... 20 28 26]
 [47 49 57 ... 20 28 26]]

[[22 26 32 ... 43 45 47]
 [22 26 32 ... 41 42 45]
 [22 26 32 ... 39 39 42]
 ...
 [ 9  9  9 ... 12 11 10]
 [ 9  9  9 ... 12 12 12]
 [ 8  9  9 ... 13 13 13]]
No eyes
1849
[[29 34 37 ... 41 39 41]
 [29 34 37 ... 40 38 39]
 [28 34 38 ... 39 37 37]
 ...
 [ 9  8  9 ... 12 11 11]
 [ 9  8  9 ... 13 12 11]
 [ 9  9  9 ... 13 13 12]]
No eyes
1850
[[24 29 35 ... 38 41 44]
 [24 30 35 ... 37 38 42]
 [24 30 36 ... 36 37 41]
 ...
 [ 8  9  9 ... 13 12 12]
 [ 7  8  9 ... 13 13 13]
 [ 6  7  9 ... 13 13 13]]
No eyes
1851
[[21 25 31 ... 43 43 44]
 [21 25 32 ... 41 40 42]
 [22 26 32 ... 40 39 40]
 ...
 [10 10 10 ... 11 11 10]
 [10 10 10 ... 12 11 10]
 [ 9 10 10 ... 12 12 11]]
No eyes
1852
[[51 53 54 ... 39 39 42]
 [52 55 56 ... 38 38 40]
 [53 57 58 ... 37 37 39]
 ...
 [ 9  9  9 ... 10  9 10]
 [ 9  9  9 ... 10 10 10]
 [ 9  8  8 ... 11 10 10]]
No eyes
1853
[[46 53 59 ... 43 42 39]
 [47 53 60 ... 43 41 39]
 [47 54 59 ... 43 40 38]
 ...
 [16 15 14 ... 12 12 11]
 [15 15 14 ... 12 12 11]
 [14 14 13 ... 13 11 11]]

[[118 113 110 ...  15  16  15]
 [114 111 109 ...  15  16  16]
 [112 110 110 ...  14  15  16]
 ...
 [  2   2   2 ...   8   8   8]
 [  1   1   2 ...   9   8   9]
 [  1   2   2 ...   9   9   9]]
Eyes
1895
[[175 170 165 ...  16  15  15]
 [171 167 161 ...  15  15  15]
 [167 162 156 ...  16  16  15]
 ...
 [  5   5   5 ...   9   9   8]
 [  3   3   3 ...   9   9   9]
 [  3   3   3 ...   9  10  10]]
Eyes
1896
[[182 179 175 ...  15  16  16]
 [178 175 172 ...  15  15  16]
 [174 171 168 ...  15  15  16]
 ...
 [  5   5   4 ...   6   4   6]
 [  5   4   4 ...   5   3   5]
 [  5   4   4 ...   4   2   4]]
Eyes
1897
[[155 152 149 ...  17  15  13]
 [151 148 146 ...  17  16  15]
 [148 146 144 ...  17  16  16]
 ...
 [  8   8   8 ...   8   6   6]
 [  7   7   7 ...   8   6   7]
 [  7   6   6 ...   8   6   7]]
Eyes
1898
[[138 141 143 ...  16  14  12]
 [144 148 150 ...  17  15  13]
 [151 155 158 ...  17  16  15]
 ...
 [  8   8   8 ...  14   8   6]
 [  8   8   8 ...  13   8   6]
 [  8   8   8 ...  12   8   6]]


[[41 35 26 19 16 16 16 17 19 21 23 28 33 38 42 47 52 55 55 53 47 39 31 25
  21 23]
 [38 31 22 19 20 23 25 27 28 30 34 40 48 54 58 63 67 69 67 63 55 46 35 27
  22 22]
 [37 27 19 17 24 31 35 37 39 42 47 53 61 67 70 72 75 75 72 66 59 49 38 29
  23 23]
 [36 25 16 15 23 34 39 42 44 49 54 59 66 69 72 73 74 73 71 67 61 51 41 31
  25 25]
 [35 25 16 15 23 33 39 42 46 51 56 61 65 67 69 71 72 71 70 68 63 54 43 33
  26 25]
 [35 25 17 17 24 32 38 41 44 50 56 61 64 66 67 68 69 68 66 64 61 55 45 34
  26 24]
 [35 26 19 18 24 31 35 37 39 45 50 56 61 62 60 59 57 55 53 53 54 52 45 34
  25 22]
 [35 26 19 17 22 27 30 29 31 35 41 48 55 56 53 48 43 40 39 41 45 47 45 36
  25 21]
 [36 27 19 16 19 24 25 23 24 27 32 39 49 54 51 44 37 33 33 37 43 47 46 39
  29 25]
 [37 29 21 17 19 23 25 23 23 24 28 35 46 53 52 45 38 34 35 40 46 51 50 43
  35 34]
 [37 31 23 20 22 25 26 26 25 26 28 34 43 52 53 48 43 41 42 47 53 56 55 46
  39 39]
 [37 32 25 23 26 28 29 29 29 30 32 35 42 51 55 54 52 52 54 58 61 62 58 49
  41 39]
 [38

[[40 35 28 21 17 17 19 21 22 24 26 31 37 42 46 51 55 57 55 49 40 32 27 24
  23 21 18 16]
 [39 33 24 18 18 22 28 31 32 35 38 44 52 58 62 65 66 65 59 50 39 31 27 24
  22 20 18 16]
 [38 31 20 14 16 25 34 39 41 45 48 54 60 66 69 70 69 65 59 50 39 32 27 23
  22 19 17 16]
 [38 29 19 13 16 25 35 41 44 48 53 58 63 67 68 68 67 64 58 49 39 31 26 22
  21 19 17 16]
 [38 29 19 14 17 26 35 40 44 49 54 59 63 66 68 67 65 62 56 48 38 30 25 21
  20 18 17 16]
 [38 30 20 16 19 27 34 38 41 46 51 57 61 64 64 61 58 53 49 43 35 29 25 21
  19 18 17 16]
 [37 29 21 16 19 26 31 33 34 38 43 50 54 56 53 49 45 41 39 36 32 28 25 21
  19 18 17 16]
 [37 30 21 16 18 23 26 26 26 28 32 39 47 51 47 41 36 34 32 30 29 27 25 22
  20 19 17 17]
 [38 31 23 18 17 20 23 23 22 23 26 32 42 49 49 44 38 33 31 29 28 28 25 22
  20 19 18 17]
 [38 33 25 19 18 20 23 23 23 23 25 29 39 49 53 50 43 36 32 30 29 30 28 24
  21 19 18 18]
 [38 34 27 21 20 22 25 26 25 25 26 30 38 48 54 53 47 41 36 34 34 33 31 26
  22 20 19 18]
 [38 35 28 23 23 26 2

[[13 12 15 ... 68 69 70]
 [12 12 16 ... 67 69 70]
 [11 12 18 ... 67 68 70]
 ...
 [25 22 22 ... 60 60 60]
 [29 24 23 ... 60 60 61]
 [32 26 23 ... 59 61 62]]
No eyes
1942
[[41 37 30 20 14 12 12 13 15 15 17 18 19 20 21 23 26 33 40 44 45 45 42 38
  29 21 16 16 19 25]
 [39 34 25 17 15 17 18 19 19 20 23 27 31 33 35 38 43 50 57 61 61 60 57 49
  39 26 18 16 18 24]
 [37 29 19 15 18 23 25 27 29 31 34 40 45 50 53 56 60 65 69 70 67 66 63 54
  41 29 20 16 18 23]
 [35 25 15 14 19 27 32 35 38 42 45 49 54 58 63 67 70 72 73 72 69 67 63 55
  42 30 21 17 17 22]
 [35 24 15 14 20 28 35 39 43 47 50 53 56 61 66 69 71 72 73 72 69 67 63 56
  44 31 21 17 17 20]
 [35 26 17 14 20 29 35 39 43 47 51 53 57 61 66 69 70 71 73 72 70 68 65 59
  48 33 23 18 18 19]
 [35 27 18 16 22 29 33 38 42 46 49 52 56 61 65 68 68 69 69 68 66 65 63 59
  48 34 23 18 18 20]
 [35 27 18 17 22 27 32 37 40 43 45 49 55 59 62 63 61 58 54 53 53 53 54 53
  46 34 24 20 21 22]
 [35 27 18 16 20 25 29 32 34 35 38 43 49 54 56 55 49 42 36 34 35 38 41 

[[23 13 12 ... 69 71 72]
 [19 12 14 ... 68 70 70]
 [15 12 15 ... 67 68 69]
 ...
 [31 24 22 ... 60 61 61]
 [35 27 23 ... 59 61 61]
 [37 29 24 ... 59 60 61]]
No eyes
1948
[[40 40 35 ... 16 20 26]
 [39 37 31 ... 16 20 25]
 [38 34 26 ... 15 19 25]
 ...
 [39 39 39 ... 35 31 29]
 [38 38 38 ... 30 28 28]
 [37 38 38 ... 24 22 24]]
No eyes
[[13 12 16 ... 70 71 72]
 [13 14 18 ... 69 70 70]
 [12 15 20 ... 67 68 69]
 ...
 [28 24 24 ... 59 60 61]
 [30 25 25 ... 59 60 61]
 [33 27 26 ... 60 61 61]]
No eyes
1949
[[40 40 38 ... 16 19 25]
 [40 38 34 ... 15 18 23]
 [39 36 30 ... 15 17 22]
 ...
 [39 39 39 ... 42 36 32]
 [39 39 39 ... 39 33 31]
 [38 38 38 ... 32 27 27]]
No eyes
[[13 13 16 ... 66 67 69]
 [11 13 18 ... 66 66 67]
 [10 13 19 ... 66 66 67]
 ...
 [24 22 23 ... 60 59 59]
 [27 23 24 ... 59 59 59]
 [29 24 24 ... 58 59 60]]
No eyes
1950
[[17 17 21 23 24 24 25 26 30 36 41 43 45 49 54 60 66 68 66 65 62 57 47 33
  21 16 16]
 [15 17 24 29 31 33 35 38 42 47 52 57 61 64 68 71 73 73 72 70 66 59 47 33
  21 

[[17 20 23 ... 17 17 29]
 [18 22 25 ... 17 17 29]
 [19 23 27 ... 17 17 29]
 ...
 [22 24 24 ... 16 15 21]
 [23 24 23 ... 16 15 21]
 [24 23 22 ... 16 16 21]]
No eyes
1957
[[15 15 19 23 25 25 26 28 33 39 43 46 49 54 59 64 70 72 72 70 67 61 52 39
  26 18 18 19]
 [12 13 20 26 31 34 35 39 44 48 53 57 61 65 68 71 73 74 73 71 69 62 52 39
  27 19 18 19]
 [12 12 18 26 34 38 41 45 49 51 55 60 65 69 70 72 72 73 73 72 69 63 52 39
  27 20 19 20]
 [13 12 18 26 33 37 41 45 49 51 55 60 66 69 70 71 72 72 72 71 69 64 54 41
  29 21 20 20]
 [13 13 19 26 32 37 41 44 47 50 55 59 64 68 70 70 70 70 69 69 68 64 55 42
  30 22 20 20]
 [13 13 19 25 32 36 40 41 44 48 54 58 61 63 63 63 61 60 60 60 60 59 54 44
  31 23 20 19]
 [12 12 17 23 29 32 33 33 36 41 48 53 56 55 52 48 44 42 42 44 46 48 49 43
  31 22 18 18]
 [13 11 16 21 25 25 23 22 24 30 38 46 50 50 44 36 30 27 28 30 34 39 43 43
  35 24 19 19]
 [14 12 16 20 22 20 17 16 18 22 28 39 48 50 44 35 28 25 25 28 32 37 44 47
  41 29 22 21]
 [17 14 17 20 20 18 17 17 18 2

[[31 31 31 ... 24 26 26]
 [31 31 31 ... 24 26 27]
 [31 31 31 ... 23 26 26]
 ...
 [32 32 31 ... 25 31 31]
 [32 32 31 ... 32 37 34]
 [32 32 32 ... 42 41 35]]
No eyes
[[  0   0   0 ... 108 114 113]
 [  1   0   0 ... 102 110 112]
 [  2   1   0 ...  95 107 111]
 ...
 [ 14  13  12 ...  74  74  74]
 [ 14  14  13 ...  71  73  73]
 [ 14  14  13 ...  60  63  65]]
No eyes
2001
[[32 32 31 ... 23 24 25]
 [31 31 31 ... 21 24 25]
 [31 31 31 ... 20 23 25]
 ...
 [32 31 31 ... 18 22 25]
 [32 32 31 ... 15 22 27]
 [32 32 31 ... 17 25 31]]
No eyes
[[  1   1   0 ...  98 119 125]
 [  1   0   0 ...  85 108 119]
 [  1   0   0 ...  74 101 117]
 ...
 [ 13  12  12 ...  73  74  74]
 [ 13  13  13 ...  70  72  74]
 [ 14  14  13 ...  57  60  64]]
No eyes
2002
[[30 30 31 ... 25 25 26]
 [30 30 31 ... 25 25 26]
 [29 30 31 ... 25 25 26]
 ...
 [31 31 31 ... 30 31 29]
 [31 31 31 ... 36 35 30]
 [31 31 31 ... 41 36 30]]
No eyes
[[ 1  0  1 ... 55 61 83]
 [ 2  1  1 ... 52 51 70]
 [ 2  1  1 ... 50 46 62]
 ...
 [ 9 11 13 ... 65 

Eyes
[[25 23 23 ... 19 14 12]
 [26 24 24 ... 19 14 12]
 [27 24 24 ... 19 14 12]
 ...
 [18 17 17 ... 17 13 12]
 [17 17 17 ... 17 13 12]
 [17 17 17 ... 16 12 11]]
No eyes
2079
[[18 19 20 ... 13 14 15]
 [18 19 20 ... 15 15 16]
 [19 20 20 ... 16 16 16]
 ...
 [11 11 11 ... 12 12 12]
 [12 12 11 ... 12 11 12]
 [12 12 10 ... 10 10 11]]
Eyes
2080
[[20 21 21 ... 14 15 15]
 [20 21 21 ... 15 15 15]
 [20 21 21 ... 15 15 14]
 ...
 [10 11 10 ... 10 10 11]
 [ 8 10  9 ...  9  9  9]
 [ 7  9  8 ...  9  9  9]]
Eyes
[[25 23 22 ... 12 13 12]
 [25 23 23 ... 12 13 12]
 [26 24 24 ... 12 13 12]
 ...
 [15 16 17 ... 12 12 12]
 [14 16 17 ... 11 11 11]
 [14 16 17 ... 11 11 11]]
No eyes
2081
[[22 23 23 ... 19 19 18]
 [22 23 23 ... 19 19 18]
 [22 23 23 ... 18 19 18]
 ...
 [ 8  8  8 ... 11 11 11]
 [ 8  8  9 ... 11 10 10]
 [ 6  7  9 ... 10  9  9]]
Eyes
[[23 22 22 ... 13 12 12]
 [24 23 23 ... 13 12 12]
 [24 24 24 ... 13 12 12]
 ...
 [16 17 19 ... 12 12 12]
 [16 17 19 ... 12 12 12]
 [16 17 19 ... 12 12 12]]
No eyes
2082


[[19 20 21 ... 17 20 22]
 [19 20 21 ... 17 20 22]
 [20 20 21 ... 18 20 22]
 ...
 [ 7  9 10 ... 20 21 20]
 [ 5  8  9 ... 17 18 19]
 [ 3  6  8 ... 14 16 17]]
Eyes
[[23 22 22 ... 13 12 12]
 [24 24 24 ... 13 12 12]
 [25 24 24 ... 13 12 12]
 ...
 [15 17 20 ... 11 11 13]
 [15 18 21 ... 12 12 12]
 [16 18 20 ... 11 12 12]]
No eyes
2107
[[19 20 21 ... 18 20 22]
 [20 20 21 ... 18 20 21]
 [19 20 21 ... 18 19 20]
 ...
 [ 5  8  9 ... 18 19 20]
 [ 3  6  8 ... 16 17 18]
 [ 2  4  6 ... 15 15 16]]
Eyes
[[26 24 24 ... 14 12 13]
 [27 25 24 ... 14 12 13]
 [26 25 24 ... 14 12 13]
 ...
 [15 15 17 ... 13 12 11]
 [14 15 18 ... 13 12 12]
 [15 16 18 ... 13 11 11]]
No eyes
2108
[[18 19 21 ... 18 21 23]
 [19 20 21 ... 19 21 23]
 [19 20 21 ... 19 21 23]
 ...
 [ 7  9 10 ... 21 21 20]
 [ 5  8  9 ... 18 19 19]
 [ 3  6  8 ... 16 17 18]]
Eyes
[[23 22 22 ... 13 12 12]
 [24 24 24 ... 13 12 12]
 [25 24 24 ... 13 12 12]
 ...
 [15 17 20 ... 11 11 13]
 [15 18 21 ... 12 12 12]
 [16 18 20 ... 11 12 12]]
No eyes
2109
[[18 19 21

Eyes
[[24 22 22 ... 13 12 12]
 [24 22 22 ... 13 12 12]
 [24 23 22 ... 13 12 12]
 ...
 [34 31 28 ... 11 11 11]
 [33 31 28 ... 11 11 11]
 [32 30 28 ... 11 11 11]]
No eyes
2134
[[10 10 10 ... 16 15 15]
 [ 9 11 10 ... 16 15 16]
 [ 7 10 11 ... 16 15 15]
 ...
 [13  9  6 ... 19 19 19]
 [14 12 11 ... 18 18 17]
 [13 14 14 ... 17 17 17]]
Eyes
[[24 22 22 ... 13 12 12]
 [24 22 22 ... 13 12 12]
 [24 23 22 ... 13 12 12]
 ...
 [34 31 28 ... 11 11 11]
 [33 31 28 ... 11 11 11]
 [32 30 28 ... 11 11 11]]
No eyes
2135
[[ 9 10 10 ... 16 15 15]
 [ 9  9 10 ... 16 15 15]
 [ 8  9 10 ... 16 15 15]
 ...
 [ 9  9 10 ... 14 13 13]
 [ 6  7  8 ... 14 13 13]
 [ 5  7  9 ... 13 13 13]]
Eyes
[[22 22 23 ... 12 12 12]
 [22 22 23 ... 12 12 12]
 [23 22 23 ... 12 12 12]
 ...
 [30 26 25 ... 11 11 13]
 [30 27 25 ... 11 11 12]
 [31 28 25 ... 11 11 12]]
No eyes
2136
[[10  9  8 ... 16 16 16]
 [ 9 10  9 ... 17 17 16]
 [ 7 10 10 ... 17 16 15]
 ...
 [ 6  4  5 ... 17 18 18]
 [10  7  7 ... 19 20 20]
 [13 12 11 ... 18 20 20]]
Eyes
[[24 

[[18 19 19 ... 16 16 15]
 [19 19 19 ... 17 16 15]
 [19 19 20 ... 17 16 16]
 ...
 [10 10  9 ... 16 18 20]
 [10 10  9 ... 14 16 17]
 [10 10  9 ... 13 14 16]]
Eyes
[[25 24 23 ... 13 12 12]
 [25 24 23 ... 13 12 12]
 [25 23 23 ... 13 12 12]
 ...
 [29 27 26 ... 11 11 11]
 [29 26 25 ... 11 11 11]
 [29 26 24 ... 11 11 11]]
No eyes
2160
[[22 22 22 ... 16 16 16]
 [22 22 23 ... 16 15 15]
 [22 22 22 ... 16 15 15]
 ...
 [ 9  9 10 ... 15 16 17]
 [10  9 11 ... 15 16 16]
 [10 10 11 ... 15 16 16]]
Eyes
[[25 24 23 ... 13 12 12]
 [25 24 23 ... 13 12 12]
 [25 23 23 ... 13 12 12]
 ...
 [29 28 26 ... 11 11 11]
 [29 27 25 ... 11 11 11]
 [29 27 24 ... 11 11 11]]
No eyes
2161
[[21 21 22 ... 22 21 19]
 [21 21 22 ... 22 21 19]
 [21 22 22 ... 22 21 19]
 ...
 [10 10 10 ... 18 18 17]
 [10  9  9 ... 18 17 16]
 [11 10  9 ... 17 15 15]]
Eyes
[[25 24 23 ... 13 12 12]
 [25 24 23 ... 13 12 12]
 [25 23 23 ... 13 12 12]
 ...
 [28 28 26 ... 11 11 11]
 [28 27 25 ... 11 11 11]
 [28 26 25 ... 11 11 11]]
No eyes
2162
[[20 21 21

Eyes
[[27 25 23 ... 14 12 13]
 [27 25 23 ... 14 12 13]
 [27 25 24 ... 14 12 13]
 ...
 [14 13 13 ... 13 11 11]
 [14 13 13 ... 13 11 11]
 [14 14 14 ... 13 11 11]]
No eyes
2187
[[19 21 22 ... 22 23 23]
 [19 21 22 ... 22 23 24]
 [20 21 21 ... 21 23 24]
 ...
 [14 15 15 ... 16 16 17]
 [11 12 13 ... 16 17 17]
 [ 9 10 10 ... 17 17 17]]
Eyes
[[25 23 21 ... 12 13 12]
 [25 23 21 ... 12 13 12]
 [25 24 22 ... 12 13 12]
 ...
 [13 14 16 ... 11 11 11]
 [13 14 17 ... 11 11 11]
 [14 15 17 ... 11 11 11]]
No eyes
2188
[[19 20 21 ... 23 22 22]
 [19 21 22 ... 22 22 23]
 [19 21 22 ... 21 22 24]
 ...
 [12 11 10 ... 17 20 22]
 [14 14 13 ... 17 17 18]
 [13 14 14 ... 16 16 16]]
Eyes
[[27 25 23 ... 14 12 13]
 [27 25 23 ... 14 12 13]
 [27 25 24 ... 14 12 13]
 ...
 [13 13 14 ... 13 11 11]
 [13 13 14 ... 13 11 11]
 [13 13 14 ... 13 11 11]]
No eyes
2189
[[18 19 20 ... 23 24 23]
 [18 19 21 ... 21 22 22]
 [19 19 21 ... 20 21 22]
 ...
 [10  9  8 ... 16 18 21]
 [12 12 11 ... 17 17 18]
 [14 14 14 ... 18 18 17]]
Eyes
[[27 

Eyes
2299
[[ 3  4  4 ... 14 12 12]
 [ 4  4  4 ... 15 13 12]
 [ 5  4  4 ... 15 13 12]
 ...
 [ 1  0  0 ... 17 17 16]
 [ 1  1  1 ... 17 17 17]
 [ 1  1  1 ... 17 17 17]]
Eyes
2300
[[ 5  5  5 ... 21 15 13]
 [ 6  5  6 ... 21 15 13]
 [ 6  5  6 ... 22 16 13]
 ...
 [ 1  1  1 ... 16 16 17]
 [ 1  1  1 ... 16 17 17]
 [ 1  1  1 ... 17 17 17]]
Eyes
2301
[[ 5  6  6 ... 36 33 28]
 [ 5  6  6 ... 36 33 28]
 [ 6  6  5 ... 36 33 28]
 ...
 [ 1  1  1 ... 25 22 18]
 [ 1  1  1 ... 25 22 18]
 [ 1  1  1 ... 25 22 19]]
Eyes
2302
[[ 4  3  3 ... 37 36 33]
 [ 5  4  4 ... 37 36 33]
 [ 6  5  5 ... 37 36 33]
 ...
 [ 1  1  0 ... 24 25 23]
 [ 1  1  0 ... 24 25 23]
 [ 1  1  0 ... 24 25 23]]
Eyes
2303
[[ 6  5  5 ... 37 37 37]
 [ 6  5  5 ... 36 36 37]
 [ 7  5  5 ... 37 37 37]
 ...
 [ 1  1  0 ... 23 23 24]
 [ 1  1  0 ... 23 23 24]
 [ 1  1  0 ... 23 23 24]]
Eyes
2304
[[25 21 15 ... 33 37 37]
 [25 21 15 ... 34 37 37]
 [24 20 15 ... 34 37 37]
 ...
 [17 10  6 ... 21 23 24]
 [17 10  6 ... 22 23 24]
 [18 11  7 ... 22 23 24]]
Eyes

[[ 7  8  8 ... 12 12 12]
 [ 8  8  9 ... 12 12 12]
 [ 8  8  8 ... 13 13 13]
 ...
 [ 1  2  3 ... 18 18 18]
 [ 2  3  4 ... 20 19 20]
 [ 2  3  4 ... 21 21 22]]
Eyes
2351
[[ 6  6  6 ... 28 22 16]
 [ 7  7  7 ... 28 22 16]
 [ 7  8  8 ... 28 21 16]
 ...
 [ 1  1  2 ... 20 18 18]
 [ 1  1  1 ... 20 19 18]
 [ 1  1  2 ... 21 20 19]]
Eyes
2352
[[ 6  5  4 ... 30 24 18]
 [ 7  6  5 ... 30 24 18]
 [ 7  6  6 ... 30 24 18]
 ...
 [ 1  2  2 ... 20 18 18]
 [ 1  2  2 ... 20 19 18]
 [ 1  1  1 ... 21 20 19]]
Eyes
2353
[[ 6  5  5 ... 33 28 22]
 [ 6  6  6 ... 33 28 22]
 [ 7  7  7 ... 33 28 22]
 ...
 [ 1  1  1 ... 24 20 18]
 [ 2  1  1 ... 24 20 18]
 [ 2  2  2 ... 24 20 19]]
Eyes
2354
[[ 6  5  5 ... 33 28 22]
 [ 7  6  5 ... 33 29 22]
 [ 8  7  6 ... 33 28 22]
 ...
 [ 1  1  1 ... 24 20 17]
 [ 1  1  1 ... 24 20 18]
 [ 2  2  2 ... 24 20 18]]
Eyes
2355
[[ 7  6  6 ... 33 28 22]
 [ 8  7  7 ... 33 28 22]
 [ 9  8  8 ... 33 28 22]
 ...
 [ 1  1  1 ... 24 20 18]
 [ 1  1  1 ... 24 20 19]
 [ 1  1  1 ... 24 21 20]]
Eyes
2356
[[ 7

Eyes
[[26 24 23 ... 14 15 15]
 [26 24 23 ... 14 15 15]
 [26 24 23 ... 14 15 15]
 ...
 [22 21 20 ... 12 13 14]
 [21 20 19 ... 12 13 14]
 [20 19 19 ... 12 13 13]]
No eyes
2381
[[22 23 23 ... 15 15 15]
 [22 23 23 ... 15 15 16]
 [23 24 23 ... 15 16 16]
 ...
 [12 10 10 ... 19 21 24]
 [14 12 10 ... 16 18 21]
 [15 13 11 ... 14 16 17]]
Eyes
[[26 24 23 ... 14 15 15]
 [26 24 23 ... 14 15 15]
 [26 24 23 ... 14 15 15]
 ...
 [22 21 20 ... 12 13 14]
 [21 20 19 ... 12 13 14]
 [20 19 19 ... 12 13 13]]
No eyes
2382
[[22 22 22 ... 15 15 15]
 [22 22 23 ... 15 16 16]
 [22 22 22 ... 16 16 16]
 ...
 [12 14 15 ... 17 18 20]
 [11 13 14 ... 16 16 18]
 [10 11 11 ... 16 16 17]]
Eyes
[[28 26 24 ... 15 14 15]
 [28 26 24 ... 15 14 15]
 [28 26 24 ... 15 14 15]
 ...
 [21 21 20 ... 14 12 13]
 [20 20 20 ... 14 12 13]
 [20 19 19 ... 13 12 13]]
No eyes
2383
[[22 22 23 ... 15 15 15]
 [22 22 22 ... 15 16 16]
 [22 22 22 ... 16 16 16]
 ...
 [12 11 11 ... 23 23 22]
 [14 11 10 ... 20 21 21]
 [14 12 10 ... 17 18 19]]
Eyes
[[26 

[[114 113 112 ...  16  16  15]
 [114 114 111 ...  17  17  17]
 [113 114 108 ...  16  16  16]
 ...
 [ 34  36  50 ...  10  15  17]
 [ 34  33  45 ...   9  13  17]
 [ 35  28  34 ...   9  11  15]]
Eyes
[[17 17 17 ... 30 32 33]
 [17 17 17 ... 30 31 33]
 [17 18 18 ... 30 31 33]
 ...
 [10 10  9 ... 15 16 16]
 [10 10  9 ... 14 14 15]
 [10 10  9 ... 12 13 14]]
Eyes
[[40 37 35 ... 57 61 63]
 [25 22 22 ... 52 56 60]
 [19 18 20 ... 53 56 61]
 ...
 [13 14 12 ...  9 11 13]
 [13 14 12 ...  8 10 12]
 [13 14 12 ...  8 10 11]]
Eyes
2403
[[111 112 113 ...  16  16  14]
 [112 113 114 ...  17  17  16]
 [112 114 114 ...  16  16  16]
 ...
 [ 72  63  49 ...  10  12  14]
 [ 77  69  57 ...  11  10  11]
 [ 81  75  66 ...  11  10  10]]
Eyes
[[16 16 17 ... 34 35 35]
 [16 16 16 ... 35 35 36]
 [15 16 17 ... 35 35 36]
 ...
 [66 68 40 ... 15 14 14]
 [66 72 45 ... 15 14 14]
 [64 75 52 ... 15 14 14]]
Eyes
[[22 22 26 ... 57 61 59]
 [17 20 26 ... 56 61 59]
 [19 21 28 ... 59 62 59]
 ...
 [13 12 12 ... 11 12 14]
 [13 12 12 ..

[[103 106 108 ...  16  17  15]
 [103 106 109 ...  14  16  15]
 [103 106 109 ...  13  14  15]
 ...
 [ 94 100 103 ...  27  26  26]
 [ 95 100 103 ...  28  27  26]
 [ 96 100 103 ...  29  28  27]]
Eyes
[[31 31 31 ... 60 58 56]
 [31 31 31 ... 57 56 54]
 [32 31 31 ... 61 60 59]
 ...
 [12 12 14 ... 11  9  9]
 [12 13 14 ... 10 10  9]
 [12 13 14 ... 10 10  9]]
Eyes
2423
[[111 111 110 ...  14  16  16]
 [112 111 110 ...  12  15  16]
 [112 112 111 ...  10  13  14]
 ...
 [105 106 107 ...  43  41  39]
 [104 106 107 ...  43  40  37]
 [104 106 107 ...  42  39  35]]
Eyes
[[15 17 19 ... 18 18 18]
 [15 17 18 ... 19 18 18]
 [14 16 17 ... 18 18 18]
 ...
 [63 63 62 ... 37 37 37]
 [62 62 61 ... 36 37 37]
 [61 61 61 ... 35 36 36]]
Eyes
[[36 34 32 ... 68 66 65]
 [35 34 32 ... 66 63 61]
 [35 33 32 ... 63 60 58]
 ...
 [15 14 13 ... 13 12 12]
 [15 13 12 ... 12 11 11]
 [15 13 12 ... 12 10 10]]
Eyes
2424
[[111 110 110 ...  14  16  16]
 [112 111 111 ...  12  14  15]
 [112 112 112 ...  10  12  14]
 ...
 [107 107 108 .

[[ 10  21  29 ...  26  28  35]
 [ 11  21  29 ...  26  28  35]
 [ 12  21  29 ...  24  28  36]
 ...
 [  4   7   8 ... 104  94  84]
 [  3   6   7 ... 106  96  85]
 [  3   6   8 ... 107  97  86]]
No eyes
2453
[[  1   2   3 ...  34  28  25]
 [  2   3   3 ...  35  28  24]
 [  3   4   4 ...  35  28  24]
 ...
 [ 17  13  11 ... 107 109 106]
 [ 18  14  11 ... 115 115 109]
 [ 18  15  11 ... 121 118 110]]
No eyes
2454
[[  2   2   2 ...  33  27  26]
 [  1   2   2 ...  34  27  27]
 [  2   2   2 ...  34  27  27]
 ...
 [ 14  14  15 ... 112 109  99]
 [ 13  13  14 ... 117 112 100]
 [ 12  12  13 ... 118 112 101]]
No eyes
[[ 33  33  32 ...  99  98  99]
 [ 32  33  32 ...  97  98  99]
 [ 30  32  33 ...  96  97  98]
 ...
 [115  92  78 ...  79  79  79]
 [129 109  92 ...  79  79  79]
 [142 128 112 ...  79  79  79]]
No eyes
2455
[[  6   6   6 ...  20  33  40]
 [  3   3   4 ...  21  33  41]
 [  3   3   5 ...  21  33  41]
 ...
 [ 17  18  17 ... 120 114 102]
 [ 16  17  17 ... 121 114 103]
 [ 16  16  17 ... 120 114

2487
[[49 52 53 ... 63 67 67]
 [48 51 52 ... 29 29 27]
 [46 48 50 ... 16 16 15]
 ...
 [ 7  8  8 ... 18 18 18]
 [ 8  9  9 ... 18 18 18]
 [ 9  9  9 ... 19 18 19]]
No eyes
[[108 106 104 ...  23  21  20]
 [108 105 102 ...  23  22  20]
 [105 104 102 ...  23  21  19]
 ...
 [ 97  98  99 ...  68  82  87]
 [ 96  97  98 ...  68  81  86]
 [ 99  99  98 ...  65  80  86]]
Eyes
[[19 25 32 ... 10 11 11]
 [22 27 33 ... 11 12 11]
 [23 28 33 ... 11 11 11]
 ...
 [29 29 31 ...  7  8  8]
 [28 28 30 ...  9  9  9]
 [28 27 28 ...  9  9  9]]
No eyes
2488
[[106 106 107 ...  24  22  21]
 [106 107 107 ...  24  23  21]
 [106 107 107 ...  23  21  19]
 ...
 [ 97  97  97 ...  58  72  83]
 [ 94  94  96 ...  55  70  82]
 [ 93  96  99 ...  52  67  82]]
No eyes
[[47 51 52 ... 28 27 30]
 [47 50 51 ... 19 18 18]
 [45 48 49 ... 13 11 11]
 ...
 [28 25 16 ... 30 24 20]
 [29 27 17 ... 31 24 20]
 [30 28 17 ... 30 24 19]]
No eyes
[[12 15 21 ...  9 10 11]
 [15 19 24 ... 10 11 12]
 [17 21 25 ... 10 11 11]
 ...
 [29 28 29 ...  6  7 

2504
[[55 57 57 ... 75 82 74]
 [56 58 58 ... 92 95 84]
 [56 58 58 ... 71 70 64]
 ...
 [34 31 29 ...  4  4  4]
 [35 33 31 ...  3  4  4]
 [36 35 34 ...  3  2  2]]
No eyes
[[104 107 108 ...  21  21  23]
 [106 109 108 ...  20  20  21]
 [105 108 108 ...  20  19  20]
 ...
 [106 105 103 ...  88  88  88]
 [104 105 105 ...  88  88  88]
 [104 105 106 ...  88  88  87]]
Eyes
[[11  4  1 ... 17 21 21]
 [13  5  1 ... 18 22 21]
 [14  8  3 ... 17 21 22]
 ...
 [15  8  3 ... 10 11 11]
 [15  8  4 ... 10 11 12]
 [16  9  5 ... 10 11 12]]
No eyes
2505
[[55 57 58 ... 74 67 71]
 [57 58 58 ... 84 78 84]
 [57 58 59 ... 64 60 62]
 ...
 [35 33 31 ...  4  3  3]
 [36 35 33 ...  4  3  3]
 [37 36 35 ...  2  3  4]]
Eyes
[[ 9 12 14 ...  0  0  0]
 [ 9 12 14 ...  1  0  0]
 [ 9 13 15 ...  1  1  2]
 ...
 [14 17 20 ...  1  2  3]
 [15 18 21 ...  1  2  3]
 [15 18 21 ...  2  2  4]]
No eyes
[[101 102 103 ...  19  19  24]
 [100 102 105 ...  19  20  23]
 [102 104 107 ...  20  20  22]
 ...
 [104 104 105 ...  88  88  88]
 [103 104 1

[[17 16 16 ... 61 63 66]
 [17 17 17 ... 54 58 62]
 [17 17 17 ... 51 53 58]
 ...
 [13 13 14 ... 14 13 12]
 [12 12 13 ... 14 13 12]
 [12 12 13 ... 15 13 12]]
Eyes
2523
[[15 15 16 ... 60 60 61]
 [16 16 16 ... 65 62 60]
 [16 16 17 ... 69 63 60]
 ...
 [13 14 15 ... 12 12 12]
 [12 13 14 ... 12 12 12]
 [12 13 14 ... 12 12 12]]
Eyes
2524
[[17 17 16 ... 63 60 57]
 [18 17 16 ... 69 69 67]
 [18 17 16 ... 62 65 68]
 ...
 [15 16 16 ... 15 14 13]
 [15 15 16 ... 15 14 13]
 [15 15 16 ... 16 15 13]]
Eyes
2525
[[17 17 16 ... 62 60 58]
 [17 17 16 ... 70 69 67]
 [18 17 17 ... 65 65 67]
 ...
 [16 16 16 ... 17 14 14]
 [15 16 16 ... 17 15 14]
 [15 15 16 ... 18 16 14]]
Eyes
2526
[[17 16 15 ... 56 65 66]
 [18 17 15 ... 61 66 60]
 [18 17 15 ... 59 59 49]
 ...
 [16 15 15 ... 14 14 15]
 [16 16 16 ... 14 14 15]
 [16 16 16 ... 14 14 15]]
Eyes
2527
[[18 17 16 ... 58 57 49]
 [18 18 16 ... 54 49 40]
 [18 18 17 ... 51 48 41]
 ...
 [15 15 15 ... 18 15 15]
 [15 15 15 ... 19 15 15]
 [16 16 16 ... 18 15 14]]
Eyes
2528
[[21

[[19 19 20 ... 59 65 71]
 [19 19 20 ... 57 60 66]
 [18 18 18 ... 61 60 63]
 ...
 [18 18 17 ... 17 15 14]
 [18 17 17 ... 17 15 14]
 [17 17 16 ... 17 15 13]]
Eyes
2562
[[91 93 95 ... 15 17 18]
 [91 93 95 ... 16 17 17]
 [92 94 95 ... 16 17 17]
 ...
 [17 20 23 ...  8 10 12]
 [18 21 24 ...  6  8  9]
 [19 22 25 ...  5  6  7]]
Eyes
[[17 17 18 ... 56 59 63]
 [17 17 19 ... 53 50 51]
 [18 18 20 ... 61 54 49]
 ...
 [18 18 17 ... 14 13 13]
 [18 18 17 ... 15 14 14]
 [18 17 16 ... 19 17 16]]
Eyes
2563
[[80 85 89 ... 17 18 18]
 [82 87 90 ... 17 19 19]
 [83 88 90 ... 18 19 20]
 ...
 [18 19 19 ... 12 15 23]
 [19 19 20 ...  8 10 14]
 [19 19 21 ...  6  7  9]]
Eyes
[[20 20 20 ... 67 69 68]
 [19 19 20 ... 66 69 71]
 [19 19 20 ... 63 69 73]
 ...
 [16 16 16 ... 13 13 14]
 [15 16 17 ... 12 13 14]
 [15 16 17 ... 12 13 14]]
Eyes
2564
[[20 21 20 ... 58 55 53]
 [20 20 20 ... 63 58 54]
 [19 19 19 ... 71 68 64]
 ...
 [15 14 15 ... 15 15 15]
 [15 15 15 ... 15 15 15]
 [15 15 16 ... 16 16 16]]
Eyes
[[16 17 18 ... 25 2

[[18 17 17 ... 15 14 14]
 [18 17 16 ... 15 14 14]
 [17 16 16 ... 15 15 14]
 ...
 [10 12 12 ... 19 18 17]
 [ 9 11 12 ... 20 19 18]
 [ 8 10 12 ... 21 19 18]]
Eyes
2604
[[ 9  7  7 ... 16 15 14]
 [ 9  8  8 ... 16 15 15]
 [ 9  8  8 ... 17 16 15]
 ...
 [14 12 12 ... 18 17 18]
 [14 14 14 ... 18 17 18]
 [15 14 14 ... 18 17 18]]
Eyes
2605
[[ 9  8  8 ... 17 17 16]
 [ 9  8  8 ... 17 17 17]
 [ 8  9  9 ... 18 18 17]
 ...
 [13 13 11 ... 19 20 18]
 [14 14 12 ... 19 19 18]
 [15 15 14 ... 18 19 18]]
Eyes
2606
[[10  7  7 ... 16 16 15]
 [ 9  7  7 ... 16 16 15]
 [ 9  8  8 ... 17 16 15]
 ...
 [ 9 10 10 ... 20 19 18]
 [11 12 11 ... 19 18 17]
 [12 13 12 ... 19 18 17]]
Eyes
2607
[[ 8  8  9 ... 16 16 15]
 [ 8  8  9 ... 17 16 15]
 [ 8  8  9 ... 17 17 16]
 ...
 [11 11 10 ... 21 19 18]
 [12 13 12 ... 20 18 18]
 [13 14 13 ... 19 18 18]]
Eyes
2608
[[11  9  7 ... 16 16 15]
 [10  8  7 ... 16 16 15]
 [ 9  7  7 ... 17 16 15]
 ...
 [ 9 11 12 ... 19 17 17]
 [11 12 13 ... 18 17 17]
 [11 12 13 ... 18 17 17]]
Eyes
2609
[[14

[[15 13 10 ... 19 18 17]
 [14 13 11 ... 19 18 17]
 [13 12 11 ... 20 18 17]
 ...
 [ 9  9 11 ... 26 24 21]
 [11 10 10 ... 24 22 20]
 [11 10  9 ... 20 19 18]]
Eyes
2652
[[11  9  9 ... 22 21 21]
 [ 9  8  9 ... 22 22 21]
 [ 8  7  8 ... 22 22 22]
 ...
 [12 14 13 ... 19 19 20]
 [12 15 14 ... 22 23 24]
 [11 14 14 ... 23 25 26]]
Eyes
2653
[[17 17 15 ... 18 17 17]
 [16 16 14 ... 18 17 17]
 [15 15 14 ... 18 17 17]
 ...
 [11 10  9 ... 23 21 19]
 [11 11 10 ... 20 19 18]
 [ 8 10 10 ... 18 17 18]]
Eyes
2654
[[17 16 16 ... 18 17 17]
 [16 15 15 ... 18 17 17]
 [15 13 13 ... 18 17 17]
 ...
 [ 3  7  9 ... 18 17 18]
 [ 2  3  6 ... 18 18 19]
 [ 3  2  4 ... 18 19 20]]
Eyes
2655
[[17 17 16 ... 20 18 18]
 [17 16 15 ... 20 19 18]
 [16 15 14 ... 20 19 18]
 ...
 [ 9  9  7 ... 26 26 24]
 [11 10  9 ... 26 27 25]
 [11 12 11 ... 23 25 24]]
Eyes
2656
[[16 17 18 ... 17 18 17]
 [18 19 19 ... 18 17 17]
 [18 19 20 ... 17 17 17]
 ...
 [11 10  6 ... 19 20 21]
 [12 12  9 ... 21 22 24]
 [12 13 11 ... 20 22 24]]
Eyes
2657
[[19

[[ 9  9  9 ... 18 18 18]
 [ 9  9  9 ... 18 18 18]
 [ 8  8  9 ... 19 19 19]
 ...
 [ 9  8  7 ... 19 19 20]
 [ 9  7  6 ... 21 21 22]
 [10  9  8 ... 20 20 21]]
Eyes
2703
[[11 11 11 ... 19 19 19]
 [10 10 10 ... 18 18 18]
 [ 9  9  9 ... 18 17 18]
 ...
 [ 8  6  6 ... 20 21 22]
 [ 8  7  6 ... 21 21 21]
 [10  9  8 ... 19 19 19]]
Eyes
2704
[[10  9  8 ... 18 18 18]
 [10  9  9 ... 18 18 18]
 [ 9  9  9 ... 18 18 18]
 ...
 [ 8  8  8 ... 18 18 18]
 [ 7  7  6 ... 18 18 19]
 [ 6  5  4 ... 18 19 20]]
Eyes
2705
[[17 17 15 ... 17 17 17]
 [16 15 14 ... 17 17 17]
 [15 13 13 ... 18 18 18]
 ...
 [ 6  4  5 ... 19 19 20]
 [ 8  5  4 ... 21 21 22]
 [10  7  4 ... 22 22 21]]
Eyes
2706
[[13 13 12 ... 18 19 18]
 [12 11 11 ... 19 20 20]
 [12 11 11 ... 19 20 19]
 ...
 [ 5  4  5 ... 18 19 19]
 [ 7  4  3 ... 20 21 22]
 [ 8  5  4 ... 22 23 22]]
Eyes
2707
[[12 11 11 ... 18 18 19]
 [11 11 11 ... 18 19 19]
 [10 10 10 ... 19 19 19]
 ...
 [ 8  8  8 ... 19 18 19]
 [ 5  7  8 ... 18 18 19]
 [ 4  6  7 ... 17 18 19]]
Eyes
2708
[[16

[[ 6  6  6 ...  9  9  8]
 [ 7  7  7 ...  9  9  8]
 [ 8  8  8 ...  9  9  9]
 ...
 [ 6  6  6 ... 10  9  8]
 [ 7  7  7 ... 10 10  9]
 [ 7  7  7 ... 10 10  9]]
Eyes
[[28 28 29 ... 98 98 98]
 [29 29 31 ... 99 98 98]
 [30 31 33 ... 99 98 97]
 ...
 [22 20 19 ... 92 92 92]
 [24 21 20 ... 92 92 92]
 [25 23 21 ... 91 91 91]]
Eyes
[[103 104 104 ...   0   0   0]
 [101 102 102 ...   0   0   0]
 [ 99 100 100 ...   0   0   0]
 ...
 [ 85  87  88 ...   0   0   0]
 [ 86  87  87 ...   0   0   0]
 [ 87  88  88 ...   0   0   0]]
Eyes
2726
[[ 6  6  6 ...  9  8  7]
 [ 7  7  7 ...  9  8  7]
 [ 8  8  8 ...  9  9  8]
 ...
 [ 6  6  6 ... 10 10  9]
 [ 7  6  7 ... 10 10 10]
 [ 7  7  7 ... 10 10 10]]
Eyes
[[26 28 28 ... 98 98 99]
 [27 29 30 ... 98 98 99]
 [29 30 32 ... 98 97 98]
 ...
 [28 26 24 ... 91 91 91]
 [29 28 26 ... 90 90 90]
 [29 29 28 ... 91 91 91]]
Eyes
[[103 104 104 ...   0   0   0]
 [101 102 102 ...   0   0   0]
 [ 99 100 100 ...   0   0   0]
 ...
 [ 85  87  88 ...   0   0   0]
 [ 86  87  87 ...   0   0

[[10 10 11 ... 12 12 12]
 [10 10 11 ... 11 12 12]
 [10 11 11 ... 11 12 14]
 ...
 [10 10 10 ... 15 15 15]
 [10 10 10 ... 15 15 15]
 [10 10 10 ... 15 15 15]]
Eyes
[[ 30  31  32 ...  98  98  99]
 [ 31  32  34 ...  99  99 100]
 [ 32  33  36 ...  99  99 100]
 ...
 [ 20  21  22 ...  89  89  89]
 [ 21  20  21 ...  89  89  89]
 [ 22  21  20 ...  89  89  88]]
Eyes
[[101 102 102 ...   0   0   0]
 [ 99 100 101 ...   0   0   0]
 [ 98 100 100 ...   0   0   0]
 ...
 [ 86  87  87 ...   0   0   0]
 [ 87  88  88 ...   0   0   0]
 [ 88  88  89 ...   0   0   0]]
Eyes
2742
[[ 9  9  9 ... 11 11 11]
 [ 9  9  9 ... 11 11 11]
 [ 9  9  9 ... 11 11 11]
 ...
 [10 10 10 ... 15 15 15]
 [10 11 11 ... 15 15 15]
 [10 10 10 ... 15 15 15]]
Eyes
[[ 31  31  32 ...  99  99 100]
 [ 32  32  34 ...  99  99 100]
 [ 32  33  35 ... 100 100 101]
 ...
 [ 21  19  20 ...  89  89  89]
 [ 22  20  19 ...  89  89  89]
 [ 24  22  20 ...  89  89  89]]
Eyes
[[101 102 102 ...   0   0   0]
 [ 99 100 101 ...   0   0   0]
 [ 99 100 100 ...   

[[ 7  9  9 ... 10 10 10]
 [ 8  9  9 ... 11 10 10]
 [ 9  9  9 ... 11 11 10]
 ...
 [10  9  9 ... 12 12 13]
 [10 10 10 ... 13 13 14]
 [10 10 10 ... 14 14 14]]
Eyes
[[ 30  32  32 ... 100 101 101]
 [ 32  33  34 ... 100 101 101]
 [ 33  34  34 ... 101 101 101]
 ...
 [ 23  19  19 ...  89  89  89]
 [ 25  22  20 ...  89  89  88]
 [ 28  25  22 ...  88  88  88]]
Eyes
[[100 101 102 ...   0   0   0]
 [ 99  99 100 ...   0   0   0]
 [ 98  99 100 ...   0   0   0]
 ...
 [ 87  87  88 ...   0   0   0]
 [ 88  88  88 ...   0   0   0]
 [ 88  88  88 ...   0   0   0]]
Eyes
2758
[[ 4  5  7 ... 10 10 10]
 [ 4  5  7 ... 10 11 10]
 [ 5  6  8 ... 11 11 10]
 ...
 [ 7  9 10 ... 13 13 13]
 [ 8  9 10 ... 14 14 14]
 [ 7  9  9 ... 13 13 13]]
Eyes
[[ 28  29  30 ...  99 100 101]
 [ 29  30  32 ... 100 101 101]
 [ 31  32  33 ... 100 101 101]
 ...
 [ 27  22  19 ...  89  89  89]
 [ 27  24  21 ...  89  88  88]
 [ 29  26  23 ...  88  88  88]]
Eyes
[[100 101 102 ...   0   0   0]
 [ 99  99 100 ...   0   0   0]
 [ 98  99 100 ...   

[[ 2  2  4 ...  5  4  4]
 [ 2  3  3 ...  6  6  5]
 [ 3  3  4 ...  7  7  6]
 ...
 [ 1  2  3 ...  9  8  8]
 [ 2  3  4 ... 10  9  8]
 [ 2  3  5 ... 10  9  9]]
Eyes
[[ 34  36  39 ...  99  99  99]
 [ 35  37  40 ...  99  99  99]
 [ 35  37  40 ...  99 100 100]
 ...
 [ 21  24  28 ...  90  89  90]
 [ 20  22  25 ...  90  89  90]
 [ 19  20  23 ...  90  89  89]]
Eyes
[[103 104 105 ...   0   0   0]
 [101 102 102 ...   0   0   0]
 [ 99 100 100 ...   0   0   0]
 ...
 [ 86  87  88 ...   0   0   0]
 [ 86  87  87 ...   0   0   0]
 [ 87  88  88 ...   0   0   0]]
Eyes
2774
[[ 0  1  2 ...  5  4  4]
 [ 0  0  1 ...  6  6  5]
 [ 0  1  2 ...  7  7  6]
 ...
 [ 0  1  2 ... 10 10  9]
 [ 1  2  3 ... 10 10  9]
 [ 1  3  4 ... 10 10  9]]
Eyes
[[ 32  34  36 ...  99  99 100]
 [ 33  35  37 ...  99 100 101]
 [ 33  35  37 ... 100 101 101]
 ...
 [ 20  19  20 ...  89  89  89]
 [ 22  19  19 ...  89  89  89]
 [ 23  21  20 ...  89  89  89]]
Eyes
[[101 102 101 ...   0   0   0]
 [ 99  99  99 ...   0   0   0]
 [ 98  99  99 ...   

[[2 2 2 ... 8 8 8]
 [3 3 3 ... 8 8 8]
 [3 4 4 ... 9 9 9]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 2 ... 2 1 0]
 [1 3 5 ... 6 4 2]]
Eyes
[[ 29  29  30 ...  98  99 100]
 [ 30  31  31 ...  98  99 100]
 [ 31  32  33 ...  99  99 100]
 ...
 [ 25  21  20 ...  89  89  89]
 [ 26  23  21 ...  89  89  89]
 [ 28  25  22 ...  89  89  89]]
Eyes
[[106 105 103 ...   0   0   0]
 [103 102 100 ...   0   0   0]
 [101 100  98 ...   0   0   0]
 ...
 [ 88  89  90 ...   0   0   0]
 [ 88  89  90 ...   0   0   0]
 [ 88  89  89 ...   0   0   0]]
Eyes
2788
[[ 3  3  4 ...  9  8  8]
 [ 4  4  4 ... 10  9  9]
 [ 4  4  4 ... 10 10  9]
 ...
 [ 1  1  1 ...  4  4  5]
 [ 0  0  1 ...  2  3  2]
 [ 1  1  2 ...  2  2  1]]
Eyes
[[ 29  30  30 ...  98  99 100]
 [ 31  31  32 ...  98  99 100]
 [ 32  33  34 ...  99  99 100]
 ...
 [ 21  20  22 ...  89  90  90]
 [ 21  20  21 ...  89  89  89]
 [ 23  21  20 ...  89  89  89]]
Eyes
[[104 105 106 ...   0   0   0]
 [102 102 103 ...   0   0   0]
 [ 99 100 101 ...   0   0   0]
 ...
 [ 87  88  88 ...   

[[14 14 14 ... 22 22 21]
 [14 14 14 ... 22 22 22]
 [14 14 15 ... 22 22 22]
 ...
 [ 5  7  8 ... 14 13 13]
 [ 7  8  8 ... 14 13 13]
 [10 10 11 ... 14 14 14]]
Eyes
2809
[[14 14 15 ... 20 20 20]
 [14 14 15 ... 21 21 21]
 [14 14 14 ... 21 21 21]
 ...
 [ 6  7  7 ... 12 13 18]
 [ 8  9  9 ... 12 13 17]
 [10 10 11 ... 14 15 16]]
Eyes
2810
[[14 14 15 ... 20 20 20]
 [14 14 15 ... 21 21 21]
 [14 14 14 ... 21 21 21]
 ...
 [ 7  7  7 ... 13 13 17]
 [ 9  9  9 ... 13 13 16]
 [ 9 10 11 ... 14 15 16]]
Eyes
2811
[[14 15 15 ... 20 20 20]
 [14 15 15 ... 21 21 21]
 [14 14 15 ... 21 21 21]
 ...
 [ 6  8  9 ... 14 14 16]
 [ 7  7  8 ... 12 12 15]
 [ 9  9  9 ... 13 13 15]]
Eyes
2812
[[15 15 15 ... 21 21 21]
 [14 14 15 ... 21 21 21]
 [14 14 14 ... 22 21 21]
 ...
 [ 7  9  9 ... 14 14 15]
 [ 8  9 10 ... 13 12 14]
 [ 9  9 12 ... 13 13 14]]
Eyes
2813
[[15 15 15 ... 21 21 20]
 [14 14 15 ... 21 21 20]
 [14 14 14 ... 21 21 20]
 ...
 [ 7  8  9 ... 12 13 18]
 [ 8  8 11 ... 13 14 17]
 [10 11 13 ... 15 15 17]]
Eyes
2814
[[14

[[17 16 14 ... 28 28 28]
 [17 15 15 ... 27 28 27]
 [17 15 15 ... 25 26 27]
 ...
 [ 9  9  9 ... 22 19 15]
 [10  9  8 ... 21 19 17]
 [10  9  8 ... 20 18 17]]
Eyes
2860
[[17 16 14 ... 28 27 25]
 [17 15 14 ... 28 28 26]
 [17 15 14 ... 27 28 27]
 ...
 [ 8  6  5 ... 16 16 17]
 [ 9  7  6 ... 17 18 19]
 [10  9  7 ... 17 18 19]]
Eyes
2861
[[17 16 14 ... 25 27 28]
 [17 16 14 ... 24 25 26]
 [17 16 14 ... 25 25 25]
 ...
 [10  8  6 ... 19 18 17]
 [10  9  7 ... 19 18 17]
 [10  9  8 ... 20 19 18]]
Eyes
2862
[[17 17 17 ... 27 27 25]
 [17 17 16 ... 28 28 26]
 [17 17 16 ... 27 27 26]
 ...
 [11 11 10 ... 17 18 18]
 [11 11 10 ... 18 18 19]
 [ 9  9  8 ... 19 19 20]]
Eyes
2863
[[16 17 17 ... 27 26 25]
 [16 17 17 ... 28 27 26]
 [16 17 17 ... 26 27 26]
 ...
 [ 9 11 11 ... 18 18 19]
 [ 9  9  9 ... 19 19 20]
 [ 6  8  8 ... 20 20 20]]
Eyes
2864
[[16 16 17 ... 26 25 23]
 [16 16 17 ... 27 26 23]
 [16 17 17 ... 27 26 24]
 ...
 [ 5  7  8 ... 20 20 22]
 [ 2  3  4 ... 19 20 21]
 [ 1  0  1 ... 17 19 20]]
Eyes
2865
[[16

[[26 27 28 ... 16 11  9]
 [27 27 28 ... 16 11  9]
 [27 28 28 ... 17 12 10]
 ...
 [31 31 31 ... 17 17 16]
 [31 31 31 ... 17 17 16]
 [32 32 32 ... 15 16 16]]
Eyes
[[ 28  30  32 ... 101 101 102]
 [ 31  32  34 ... 102 102 101]
 [ 32  33  35 ... 102 102 102]
 ...
 [ 20  19  20 ...  87  88  88]
 [ 23  20  19 ...  87  88  88]
 [ 26  22  20 ...  87  88  88]]
Eyes
[[20 27 35 ...  7  2  1]
 [20 27 34 ... 13  5  2]
 [19 24 30 ... 28 14  5]
 ...
 [16 21 24 ...  6  2  0]
 [15 21 24 ...  8  2  0]
 [15 20 23 ...  9  3  0]]
Eyes
2895
[[ 6 11 18 ...  7  7  7]
 [ 6 11 18 ...  8  8  8]
 [ 6 12 19 ...  8  8  8]
 ...
 [22 28 31 ... 17 17 17]
 [21 28 31 ... 16 17 18]
 [22 28 32 ... 15 16 18]]
Eyes
[[ 36  40  42 ... 102 102 102]
 [ 37  40  42 ... 103 102 102]
 [ 37  40  42 ... 102 102 101]
 ...
 [ 24  27  29 ...  87  87  87]
 [ 23  25  28 ...  87  87  87]
 [ 21  23  26 ...  87  87  87]]
Eyes
[[16 20 27 ...  3  1  1]
 [16 20 27 ...  6  2  1]
 [15 19 24 ... 15  5  1]
 ...
 [13 16 21 ...  2  0  0]
 [14 16 21 ..

[[11 19 23 ...  2  2  2]
 [12 19 23 ...  3  3  3]
 [13 19 24 ...  4  4  4]
 ...
 [28 31 31 ... 15 15 15]
 [29 31 31 ... 15 15 15]
 [28 31 31 ... 15 15 15]]
Eyes
[[37 40 43 ... 98 97 97]
 [38 41 43 ... 97 95 96]
 [38 41 43 ... 96 95 95]
 ...
 [20 23 26 ... 88 88 89]
 [19 21 23 ... 88 88 88]
 [19 20 22 ... 88 88 88]]
Eyes
[[23 31 35 ... 25 11  3]
 [21 27 31 ... 42 21  7]
 [19 24 28 ... 58 33 12]
 ...
 [18 23 23 ...  4  1  0]
 [18 23 23 ...  4  1  0]
 [19 23 24 ...  5  1  0]]
Eyes
2911
[[ 0  0  0 ...  3  2  2]
 [ 0  0  0 ...  4  2  2]
 [ 0  1  1 ...  5  3  3]
 ...
 [13 12 13 ... 16 15 16]
 [13 13 13 ... 16 16 15]
 [13 13 13 ... 16 16 16]]
Eyes
[[ 35  37  39 ... 100  98  97]
 [ 35  37  40 ...  99  97  96]
 [ 35  37  40 ...  98  96  95]
 ...
 [ 19  21  24 ...  88  88  88]
 [ 18  19  21 ...  88  88  88]
 [ 19  19  20 ...  88  88  88]]
Eyes
[[30 35 33 ... 25 11  3]
 [26 31 30 ... 42 21  7]
 [24 28 29 ... 58 33 12]
 ...
 [23 24 19 ...  3  1  0]
 [23 24 19 ...  4  1  0]
 [23 24 19 ...  4  1  0]

[[21 25 28 ...  3  3  3]
 [21 25 28 ...  4  4  4]
 [21 25 28 ...  5  5  5]
 ...
 [33 33 32 ... 15 15 15]
 [33 33 32 ... 15 15 15]
 [33 32 32 ... 14 14 14]]
Eyes
[[ 33  35  36 ... 101 101  99]
 [ 34  35  37 ... 101 100  98]
 [ 34  35  37 ... 100  99  97]
 ...
 [ 19  17  18 ...  87  87  87]
 [ 22  18  18 ...  88  87  87]
 [ 25  21  18 ...  87  87  87]]
Eyes
[[25 34 37 ... 30 19 10]
 [23 31 34 ... 53 34 18]
 [20 27 30 ... 81 51 28]
 ...
 [20 24 22 ...  6  2  0]
 [20 24 22 ...  7  3  1]
 [20 24 22 ...  8  3  1]]
Eyes
2927
[[28 29 30 ...  6  6  6]
 [28 29 29 ...  7  7  7]
 [28 29 29 ...  8  8  8]
 ...
 [32 33 33 ... 15 15 13]
 [32 32 33 ... 15 15 14]
 [32 33 33 ... 15 15 15]]
Eyes
[[ 31  33  35 ... 102 101 101]
 [ 33  35  36 ... 101 101 100]
 [ 34  35  37 ... 101 101  99]
 ...
 [ 19  18  19 ...  87  87  87]
 [ 20  17  18 ...  87  87  87]
 [ 23  19  18 ...  88  87  87]]
Eyes
[[16 17 25 ...  3  1  1]
 [16 17 25 ...  5  2  1]
 [16 17 25 ...  9  3  1]
 ...
 [12 15 20 ...  1  0  0]
 [12 15 19 ..

[[ 0  0  0 ...  4  4  4]
 [ 0  0  0 ...  5  5  6]
 [ 0  0  0 ...  6  7  7]
 ...
 [ 0  0  0 ... 11 10 10]
 [ 0  0  0 ... 11 11 10]
 [ 1  0  0 ... 11 11 11]]
Eyes
[[32 34 36 ... 98 96 96]
 [33 34 37 ... 97 95 94]
 [33 35 37 ... 96 94 94]
 ...
 [18 21 23 ... 87 86 86]
 [19 20 22 ... 87 86 86]
 [20 20 21 ... 87 86 86]]
Eyes
[[16 19 26 ...  2  1  1]
 [16 18 25 ...  3  1  1]
 [15 17 22 ...  5  1  1]
 ...
 [12 14 20 ...  0  0  0]
 [12 14 20 ...  0  0  0]
 [12 15 22 ...  1  0  0]]
Eyes
2943
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  2  1  1]
 [ 0  0  0 ...  3  3  2]
 ...
 [ 0  0  0 ...  9  9  9]
 [ 0  0  0 ...  9  9  9]
 [ 1  1  0 ... 10  9  9]]
Eyes
[[ 34  36  39 ... 100  99  97]
 [ 34  36  40 ... 100  98  96]
 [ 34  37  40 ...  99  97  95]
 ...
 [ 24  26  29 ...  87  87  87]
 [ 22  25  27 ...  87  87  86]
 [ 21  23  25 ...  87  87  86]]
Eyes
[[16 19 26 ...  2  1  1]
 [16 18 25 ...  3  1  1]
 [15 17 22 ...  5  2  1]
 ...
 [12 14 20 ...  1  0  0]
 [12 14 20 ...  1  0  0]
 [12 15 22 ...  1  0  0]

[[ 1  1  1 ...  7  6  6]
 [ 1  1  1 ...  7  7  7]
 [ 1  1  1 ...  8  8  8]
 ...
 [ 1  1  1 ... 11 11 11]
 [ 1  1  1 ... 12 12 12]
 [ 2  2  2 ... 12 13 13]]
Eyes
[[32 33 35 ... 96 95 95]
 [32 33 35 ... 95 94 94]
 [32 34 36 ... 96 95 94]
 ...
 [25 25 27 ... 87 87 87]
 [23 23 25 ... 87 87 86]
 [21 22 23 ... 87 87 86]]
Eyes
[[17 19 25 ...  1  1  1]
 [16 18 24 ...  1  1  1]
 [16 18 22 ...  1  1  1]
 ...
 [12 14 18 ...  0  0  0]
 [11 14 18 ...  0  0  0]
 [11 13 18 ...  0  0  0]]
Eyes
2961
[[ 1  0  0 ...  8  8  8]
 [ 1  0  0 ...  9  9  8]
 [ 1  1  1 ...  9  9  9]
 ...
 [ 1  2  3 ... 11 11 11]
 [ 1  2  3 ... 11 11 11]
 [ 2  3  4 ... 11 11 11]]
Eyes
[[29 31 32 ... 96 96 96]
 [30 31 32 ... 95 95 95]
 [30 31 32 ... 94 94 94]
 ...
 [22 22 22 ... 87 86 86]
 [24 23 22 ... 86 86 86]
 [26 24 21 ... 86 86 86]]
Eyes
[[16 18 25 ...  1  1  1]
 [17 19 25 ...  1  1  1]
 [16 18 24 ...  1  1  1]
 ...
 [13 15 19 ...  0  0  0]
 [13 16 20 ...  0  0  0]
 [12 15 20 ...  0  0  0]]
Eyes
2962
[[ 0  1  3 ...  9  9  9]

Eyes
[[25 24 23 ... 12 12 12]
 [25 24 23 ... 12 12 12]
 [25 24 23 ... 12 12 12]
 ...
 [16 17 17 ... 13 12 12]
 [16 16 17 ... 13 12 12]
 [15 16 17 ... 13 12 12]]
No eyes
2979
[[16 16 13 ... 24 23 21]
 [16 14 12 ... 23 23 22]
 [15 13 10 ... 22 23 22]
 ...
 [ 9 10 10 ... 15 14 13]
 [ 7  8  9 ... 15 13 14]
 [ 5  6  7 ... 14 12 13]]
Eyes
[[24 23 22 ... 12 12 12]
 [24 23 22 ... 12 12 12]
 [24 23 22 ... 12 12 12]
 ...
 [17 17 17 ... 12 12 12]
 [17 17 17 ... 12 12 12]
 [16 17 17 ... 12 12 12]]
No eyes
2980
[[17 17 15 ... 23 24 23]
 [17 16 14 ... 22 22 23]
 [17 16 14 ... 22 22 22]
 ...
 [ 8  9 10 ... 15 15 14]
 [ 6  7  8 ... 16 15 13]
 [ 5  5  6 ... 16 14 12]]
Eyes
2981
[[16 17 17 ... 24 23 21]
 [16 17 16 ... 23 23 22]
 [17 16 15 ... 23 23 23]
 ...
 [ 7  8  9 ... 15 13 14]
 [ 5  6  7 ... 14 12 13]
 [ 5  5  6 ... 14 12 12]]
Eyes
2982
[[16 17 16 ... 23 23 23]
 [16 17 15 ... 22 22 22]
 [16 16 13 ... 22 23 23]
 ...
 [ 8  9 10 ... 15 15 14]
 [ 6  7  8 ... 16 15 13]
 [ 5  5  6 ... 16 14 12]]
Eyes
298

[[16 16 17 ... 26 25 23]
 [16 16 16 ... 26 25 24]
 [16 16 15 ... 25 25 24]
 ...
 [12 13 14 ... 21 19 17]
 [10 12 13 ... 20 19 18]
 [ 8 10 11 ... 20 19 19]]
Eyes
[[23 22 21 ... 12 12 12]
 [22 22 21 ... 12 12 12]
 [22 22 21 ... 12 12 12]
 ...
 [16 16 17 ... 13 12 12]
 [16 16 17 ... 13 12 12]
 [16 16 17 ... 13 12 12]]
No eyes
3012
[[16 17 17 ... 24 22 20]
 [16 17 17 ... 25 23 21]
 [16 16 16 ... 25 24 22]
 ...
 [13 14 13 ... 18 16 14]
 [13 14 14 ... 19 16 14]
 [12 13 13 ... 19 18 16]]
Eyes
[[22 21 21 ... 12 12 12]
 [22 21 22 ... 12 12 12]
 [22 21 22 ... 12 12 12]
 ...
 [16 17 17 ... 12 12 13]
 [16 17 17 ... 12 12 13]
 [16 17 17 ... 12 12 13]]
No eyes
3013
[[17 17 17 ... 28 26 25]
 [16 16 16 ... 27 26 25]
 [16 15 15 ... 25 25 25]
 ...
 [13 12 11 ... 21 18 16]
 [14 14 13 ... 21 19 18]
 [14 15 14 ... 21 20 19]]
Eyes
[[23 22 21 ... 12 12 12]
 [22 22 21 ... 12 12 12]
 [22 22 21 ... 12 12 12]
 ...
 [16 16 17 ... 13 12 12]
 [16 16 17 ... 13 12 12]
 [16 16 17 ... 13 12 12]]
No eyes
3014
[[16 16 16

[[14 14 14 ... 16 16 16]
 [15 15 15 ... 16 16 15]
 [15 16 15 ... 16 16 15]
 ...
 [13 14 15 ... 16 15 15]
 [12 13 15 ... 16 15 15]
 [12 13 13 ... 16 15 16]]
Eyes
[[23 22 21 ... 12 12 12]
 [24 23 21 ... 12 12 12]
 [25 23 21 ... 12 12 12]
 ...
 [17 17 17 ... 12 13 12]
 [17 17 17 ... 12 13 12]
 [16 16 17 ... 12 13 12]]
No eyes
3043
[[13 13 13 ... 15 15 15]
 [14 14 14 ... 15 16 15]
 [15 15 15 ... 15 15 15]
 ...
 [15 16 15 ... 17 17 17]
 [14 15 15 ... 17 17 16]
 [13 14 15 ... 17 17 17]]
Eyes
[[23 22 21 ... 12 12 12]
 [24 23 21 ... 12 12 12]
 [25 23 21 ... 12 12 12]
 ...
 [17 17 17 ... 12 13 12]
 [17 17 17 ... 12 13 12]
 [16 16 17 ... 12 13 12]]
No eyes
3044
[[78 79 80 ... 17 17 15]
 [78 79 81 ... 18 18 16]
 [79 80 81 ... 18 18 16]
 ...
 [63 63 61 ...  6  7  8]
 [60 60 59 ...  7  7  8]
 [57 58 56 ...  7  8  9]]
Eyes
3045
[[78 78 79 ... 18 17 15]
 [78 79 80 ... 18 18 16]
 [79 80 81 ... 18 18 16]
 ...
 [63 63 62 ...  6  6  7]
 [60 60 59 ...  7  6  7]
 [57 58 58 ...  7  7  8]]
Eyes
3046
[[79 79 

[[68 68 67 ... 12 12 13]
 [70 70 69 ... 12 12 12]
 [72 71 71 ... 13 12 12]
 ...
 [24 23 25 ... 11 10  9]
 [22 22 25 ... 11 11 10]
 [22 22 24 ... 11 11 11]]
Eyes
3094
3095
[[69 68 69 ... 14 13 11]
 [70 70 70 ... 14 13 12]
 [71 71 71 ... 15 13 12]
 ...
 [32 35 39 ...  3  4  4]
 [30 35 38 ...  3  3  5]
 [30 34 38 ...  3  3  5]]
Eyes
3096
[[70 70 69 ... 14 13 12]
 [72 72 71 ... 13 14 13]
 [72 72 72 ... 13 14 14]
 ...
 [23 23 25 ...  5  4  3]
 [22 23 25 ...  5  3  2]
 [22 23 25 ...  6  4  3]]
Eyes
3097
[[77 77 77 ... 17 17 17]
 [77 77 77 ... 17 17 18]
 [77 77 77 ... 16 17 18]
 ...
 [23 22 23 ... 13 11 10]
 [23 23 23 ... 11 11 10]
 [23 22 23 ... 11 11 10]]
Eyes
3098
[[75 75 75 ... 17 16 15]
 [74 74 74 ... 17 16 16]
 [75 74 74 ... 17 16 16]
 ...
 [22 24 26 ... 10 10  9]
 [21 23 25 ...  9  9  8]
 [21 23 24 ...  9  8  7]]
Eyes
3099
[[78 79 79 ... 16 14 12]
 [78 78 78 ... 16 15 13]
 [78 78 78 ... 16 15 14]
 ...
 [24 23 22 ...  8  7  7]
 [22 21 20 ...  8  7  7]
 [20 19 19 ...  9  8  8]]
Eyes
3100

[[12 12 12 ... 18 17 17]
 [12 12 12 ... 18 17 17]
 [12 12 12 ... 18 17 17]
 ...
 [ 8  9 10 ... 21 21 19]
 [ 8  9 10 ... 20 20 19]
 [ 7  8 10 ... 18 19 19]]
Eyes
[[21 20 19 ... 13 12 12]
 [22 21 19 ... 13 12 12]
 [22 21 19 ... 13 12 12]
 ...
 [22 20 18 ... 13 11 12]
 [22 19 17 ... 13 11 12]
 [22 19 16 ... 13 12 12]]
No eyes
3142
[[12 12 12 ... 19 18 17]
 [12 12 12 ... 19 18 18]
 [12 12 12 ... 19 19 18]
 ...
 [ 8  8 10 ... 20 18 16]
 [ 7  7  9 ... 22 19 17]
 [ 5  6  7 ... 21 20 18]]
Eyes
[[21 20 19 ... 13 12 12]
 [22 21 19 ... 13 12 12]
 [22 21 19 ... 13 12 12]
 ...
 [26 22 19 ... 13 11 12]
 [27 22 19 ... 13 11 12]
 [26 22 19 ... 13 12 12]]
No eyes
3143
[[13 14 14 ... 15 15 15]
 [13 14 14 ... 16 15 15]
 [13 14 14 ... 15 15 16]
 ...
 [ 8  7  8 ... 21 21 17]
 [ 8  8  9 ... 20 21 17]
 [ 8  8  9 ... 19 20 17]]
Eyes
3144
[[12 12 12 ... 15 15 15]
 [12 12 12 ... 16 16 15]
 [12 12 12 ... 16 17 17]
 ...
 [ 8  6  5 ... 13 14 15]
 [ 9  7  6 ... 14 15 15]
 [10  9  8 ... 15 15 14]]
Eyes
[[25 23 21 ..

[[14 14 15 ... 15 15 16]
 [14 14 15 ... 14 14 15]
 [14 14 15 ... 13 14 15]
 ...
 [ 1  1  1 ... 15 15 15]
 [ 2  1  1 ... 16 15 14]
 [ 2  1  1 ... 16 15 14]]
Eyes
3175
[[14 14 14 ... 16 17 17]
 [13 14 14 ... 15 16 17]
 [13 14 14 ... 15 16 16]
 ...
 [ 2  2  2 ... 18 17 16]
 [ 1  2  3 ... 18 17 17]
 [ 2  2  2 ... 18 18 18]]
Eyes
[[22 21 20 ... 12 13 12]
 [22 21 20 ... 12 13 12]
 [22 20 20 ... 12 13 12]
 ...
 [15 15 16 ... 11 12 11]
 [15 15 16 ... 11 12 11]
 [13 14 15 ... 11 12 11]]
No eyes
3176
[[14 14 14 ... 17 18 20]
 [14 14 14 ... 16 17 18]
 [14 14 14 ... 16 16 18]
 ...
 [ 1  2  3 ... 19 19 18]
 [ 4  5  6 ... 20 19 18]
 [ 7  9  9 ... 18 18 17]]
Eyes
[[21 20 19 ... 13 12 13]
 [20 20 19 ... 13 12 13]
 [21 20 18 ... 13 12 13]
 ...
 [14 15 16 ... 13 11 11]
 [16 16 16 ... 12 11 12]
 [15 16 16 ... 13 11 12]]
No eyes
3177
[[14 14 14 ... 15 15 16]
 [14 14 14 ... 13 14 16]
 [14 14 14 ... 13 14 16]
 ...
 [ 1  1  1 ... 21 20 20]
 [ 1  1  1 ... 22 21 20]
 [ 2  3  3 ... 22 20 20]]
Eyes
[[22 21 20 ..

[[16 16 16 ... 21 20 19]
 [17 17 16 ... 21 20 19]
 [17 16 15 ... 21 20 19]
 ...
 [ 3  5  5 ... 15 15 15]
 [ 3  4  4 ... 15 15 16]
 [ 5  4  3 ... 15 15 16]]
Eyes
[[22 20 20 ... 14 12 12]
 [21 21 20 ... 14 12 12]
 [21 21 19 ... 14 12 12]
 ...
 [19 17 16 ... 12 11 11]
 [19 17 16 ... 12 11 12]
 [19 17 16 ... 12 11 12]]
No eyes
3207
[[14 15 16 ... 20 21 21]
 [15 15 16 ... 20 21 21]
 [15 16 17 ... 20 21 21]
 ...
 [ 4  4  2 ... 14 15 15]
 [ 4  3  2 ... 16 17 19]
 [ 6  4  3 ... 17 18 19]]
Eyes
[[23 21 20 ... 13 12 11]
 [23 21 20 ... 13 12 11]
 [23 21 20 ... 13 12 11]
 ...
 [20 18 17 ... 12 11 11]
 [20 18 17 ... 12 11 12]
 [20 18 17 ... 12 11 12]]
No eyes
3208
[[ 8  8  8 ... 20 19 17]
 [ 8  8  9 ... 20 20 18]
 [ 8  8  9 ... 21 20 19]
 ...
 [10 10  9 ... 11 11 13]
 [ 9 11  9 ... 14 14 14]
 [ 7 10  9 ... 17 18 16]]
Eyes
[[24 23 21 ... 13 12 11]
 [24 23 22 ... 13 12 11]
 [24 23 22 ... 13 12 11]
 ...
 [22 20 18 ... 12 11 12]
 [22 20 18 ... 12 11 12]
 [22 19 18 ... 12 11 12]]
No eyes
3209
[[16 17 16

So, now for a note:
    
    If you want to detect cars or pedestrians on a road, you can do that. It's the exact same code as above.
    Just replace whatever classifier you want to use !!!
    
However for uncommon objects, you'll have to create your own classifier !