In [2]:
import numpy as np
np.random.seed(2020)

In [7]:
#Let's create the input
X=[]
n_rows=int(input("Enter rows : "))
n_cols=int(input("Enter columns : "))

for i in range(n_rows):
    X_rows=[]
    for j in range(n_cols):
        X_rows.append(np.random.uniform(-1,3))
    X.append(X_rows)
X=np.array(X).reshape((3,4))
X

Enter rows : 3
Enter columns : 4


array([[ 0.06472931, -0.37710168,  0.30283787, -0.37303677],
       [-0.66150843,  1.44234742,  2.13703389,  2.77588498],
       [ 2.55018558,  2.72823587,  0.54400777,  1.26985124]])

In [14]:
#Next we create layers through class objects
class Layer_dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs,n_neurons) #initialize weights
        self.biases = np.zeros((1,n_neurons)) #one bias per neuron
    def forward(self,inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [15]:
#Hence, we can now create any number of layers:
layer1 = Layer_dense(4,5)
layer2 = Layer_dense(5,2)

In [16]:
#and call each of the methods to get weights and biases
layer1.forward(X) #forward propagate inputs
print(layer1.output)

[[ 0.0016788  -0.15854329 -0.1063009   0.02825316 -0.05246507]
 [ 0.01663756  0.33785223 -0.3501309  -0.77473849 -0.20282077]
 [-0.19122752  0.16900033 -0.5024816  -0.39323234  0.10808751]]


In [17]:
layer2.forward(layer1.output) #since output of layer 1 is input of layer 2 !
print(layer2.output)

[[ 0.0046082   0.00621215]
 [ 0.11736978 -0.09342035]
 [ 0.0053907  -0.02026518]]


We are still missing our activation function, so let's do that